from shared.schemas.core.assignment import (
    Assignment,
    AssignmentSource,
    AssignmentsRecurrencesResult,
)
from shared.schemas.core.attribute import Attribute, AttributeOwnerType
from shared.schemas.core.breach import Breach, ObjectiveCategory, Variable
from shared.schemas.core.config import Config
from shared.schemas.core.constraint import (
    Block,
    BlockNameOptions,
    BlockTypeOptions,
    ConfigurationConstraintPenalty,
    Constraint,
    ConstraintBuild,
    ConstraintBuildAugmented,
    ConstraintFai,
    ConstraintFil,
    ConstraintOperator,
    ConstraintOrd,
    Constraints,
    ConstraintSeq,
    ConstraintSum,
    ConstraintType,
    CoveragePenalty,
    MissingAttribute,
    Penalties,
    Penalty,
    ShiftWorkerOption,
    SWOIdTypes,
    SystemConstraintPenalty,
    Template,
    TemplateBlock,
    UserConstraintPenalty,
    VarDaySelectorOptions,
    VarShiftSelectorOptions,
    VarWorkerSelectorOptions,
)
from shared.schemas.core.coverage import Coverage
from shared.schemas.core.dim_entry import DimEntry
from shared.schemas.core.dimension import (
    Dimension,
    DimensionAndDimEntries,
    DimensionEntryType,
    DimensionType,
    NewDimension,
)
from shared.schemas.core.email import (
    EmailMessage,
    EmailPriority,
    EmailQueueMessage,
    EmailType,
)
from shared.schemas.core.engine import (
    ConfigurationConstraints,
    CustomSolverParams,
    EngineInputs,
    EngineInputsAugmented,
    EngineOutputs,
    EngineOutputsAugmented,
    ModelConfig,
    ModelSetup,
    SolverParams,
    SolveStrategy,
    SystemConstraints,
)
from shared.schemas.core.export_options import (
    ExportOptions,
    ExportPeriodOptions,
)
from shared.schemas.core.link_shift import LinkShift, LSChange
from shared.schemas.core.model_output import ModelOutput, ModelOutputStatus
from shared.schemas.core.multitasking import (
    MultitaskingGroup,
    MultitaskingGroupType,
    ShiftDemandConcurrency,
    ShiftDemandConcurrencyRequest,
    ShiftDemandConcurrencyResponse,
)
from shared.schemas.core.notification import (
    Notification,
    NotificationDTO,
    NotificationType,
)
from shared.schemas.core.notification_preferences import (
    NotificationPreferences,
    NotificationPreferencesDTO,
)
from shared.schemas.core.recurrence import (
    FrequencyType,
    MonthRepeatType,
    OccurrenceInfo,
    OccurrenceType,
    RecurrenceEndType,
    RecurrenceExclusion,
    RecurrenceRule,
    RecurrenceUpdateScope,
)
from shared.schemas.core.replacement import (
    AssignmentImplication,
    ConstraintHits,
    FilterHits,
    LTMIndicator,
    MonthlyDutiesImplications,
    MostConstrainingReason,
    OverlapHits,
    ReplacementCandidate,
    ReplacementCategory,
    ReplacementImplications,
    RequestHits,
    SwapAssignmentInfo,
    SwapValidationResult,
    WeeklyWorkTimeImplications,
)
from shared.schemas.core.request import (
    FulfillmentStatus,
    Request,
    RequestAugmented,
    RequestStatus,
    RequestType,
)
from shared.schemas.core.schedule import (
    DuplicateOptions,
    DuplicateRequest,
    DuplicateResult,
    Period,
    QuickStaffing,
    Schedule,
    ScheduleStatus,
    WorkTimeTable,
    WorkTimeTableData,
)
from shared.schemas.core.shift import (
    Shift,
    ShiftLeaveType,
    ShiftRestType,
    ShiftType,
    Staffing,
)
from shared.schemas.core.shift_demand import ShiftDemand
from shared.schemas.core.shift_demand_exclusion import ShiftDemandExclusion
from shared.schemas.core.shift_demand_new import (
    DemandsResult,
    ShiftDemandCriteria,
    ShiftDemandNew,
    ShiftDemandSource,
)
from shared.schemas.core.shift_demand_template import (
    ShiftDemandTemplate,
    TemplateType,
    TemplateWeekData,
    create_template_from_demands,
)
from shared.schemas.core.solve_task_status import (
    ResultModel,
    ShiftDateCell,
    SolveRequest,
    SolveRequestStatus,
    SolverOutputMetadata,
    SolverOutputStatus,
    SolveScope,
    SolveScopeType,
    SolveTaskStatus,
    SQSSolveMessage,
    SQSSolveQueueMessage,
    WorkerDateCell,
)
from shared.schemas.core.specialty import Specialty
from shared.schemas.core.stats import (
    HeaderUnitOptions,
    Stats,
    StatsHeader,
    StatsOptions,
    StatsTimeFrameOptions,
    StatsUnitOptions,
    StatsValue,
)
from shared.schemas.core.swap import (
    SwapAuditData,
    SwapBid,
    SwapRequest,
    SwapStatus,
    SwapType,
)
from shared.schemas.core.task import TaskServices
from shared.schemas.core.team import (
    MembershipForTeamWithMembership,
    Team,
    TeamWithMembership,
)
from shared.schemas.core.team_generation_settings import TeamGenerationSettings
from shared.schemas.core.team_invitation import (
    EnrichedTeamInvitation,
    TeamInvitation,
    TeamInvitationStatus,
    TeamInvitationType,
)
from shared.schemas.core.team_membership import (
    INVITE_TYPE_ROLE_MAP,
    TEAM_ROLE_TO_AUTHZ_ROLE,
    TeamMembership,
    TeamMembershipRole,
)
from shared.schemas.core.user import (
    Language,
    PasswordData,
    SystemRole,
    User,
    UserWithMembership,
)
from shared.schemas.core.worker import Worker, WorkerDates

# pylint: disable=R0801
__all__ = [
    "Attribute",
    "AssignmentSource",
    "AssignmentsRecurrencesResult",
    "AttributeOwnerType",
    "Config",
    "Assignment",
    "EmailMessage",
    "EmailPriority",
    "EmailQueueMessage",
    "EmailType",
    "Notification",
    "NotificationDTO",
    "NotificationType",
    "NotificationPreferences",
    "NotificationPreferencesDTO",
    "Block",
    "BlockNameOptions",
    "BlockTypeOptions",
    "ConfigurationConstraintPenalty",
    "Constraint",
    "ConstraintBuild",
    "ConstraintBuildAugmented",
    "ConstraintFai",
    "ConstraintFil",
    "ConstraintOperator",
    "ConstraintOrd",
    "Constraints",
    "ConstraintSeq",
    "ConstraintSum",
    "ConstraintType",
    "CoveragePenalty",
    "MissingAttribute",
    "Penalties",
    "Penalty",
    "ShiftWorkerOption",
    "SWOIdTypes",
    "SystemConstraintPenalty",
    "Template",
    "TemplateBlock",
    "UserConstraintPenalty",
    "VarDaySelectorOptions",
    "VarShiftSelectorOptions",
    "VarWorkerSelectorOptions",
    "Coverage",
    "ShiftDemand",
    "ShiftDemandExclusion",
    "DemandsResult",
    "ShiftDemandCriteria",
    "ShiftDemandNew",
    "ShiftDemandSource",
    "ShiftDemandTemplate",
    "TemplateType",
    "TemplateWeekData",
    "create_template_from_demands",
    "Dimension",
    "DimensionAndDimEntries",
    "DimensionEntryType",
    "DimensionType",
    "NewDimension",
    "DimEntry",
    "ConfigurationConstraints",
    "CustomSolverParams",
    "EngineInputs",
    "EngineInputsAugmented",
    "EngineOutputs",
    "EngineOutputsAugmented",
    "ModelConfig",
    "ModelSetup",
    "SolverParams",
    "SolveStrategy",
    "SystemConstraints",
    "ExportOptions",
    "ExportPeriodOptions",
    "ModelOutput",
    "ModelOutputStatus",
    "FrequencyType",
    "MonthRepeatType",
    "OccurrenceInfo",
    "RecurrenceEndType",
    "RecurrenceExclusion",
    "RecurrenceRule",
    "OccurrenceType",
    "RecurrenceUpdateScope",
    "FulfillmentStatus",
    "Request",
    "RequestAugmented",
    "RequestStatus",
    "RequestType",
    "Breach",
    "ObjectiveCategory",
    "ConstraintHits",
    "FilterHits",
    "LTMIndicator",
    "MonthlyDutiesImplications",
    "MostConstrainingReason",
    "OverlapHits",
    "ReplacementCandidate",
    "ReplacementCategory",
    "ReplacementImplications",
    "RequestHits",
    "AssignmentImplication",
    "SwapAssignmentInfo",
    "SwapValidationResult",
    "WeeklyWorkTimeImplications",
    "DuplicateOptions",
    "DuplicateRequest",
    "DuplicateResult",
    "Period",
    "QuickStaffing",
    "Schedule",
    "ScheduleStatus",
    "Variable",
    "WorkTimeTable",
    "WorkTimeTableData",
    "SwapAuditData",
    "SwapBid",
    "SwapRequest",
    "SwapStatus",
    "SwapType",
    "LinkShift",
    "LSChange",
    "MultitaskingGroup",
    "MultitaskingGroupType",
    "ShiftDemandConcurrency",
    "ShiftDemandConcurrencyRequest",
    "ShiftDemandConcurrencyResponse",
    "Shift",
    "ShiftLeaveType",
    "ShiftRestType",
    "ShiftType",
    "Staffing",
    "HeaderUnitOptions",
    "StatsOptions",
    "StatsTimeFrameOptions",
    "StatsUnitOptions",
    "Stats",
    "StatsHeader",
    "StatsValue",
    "TaskServices",
    "Specialty",
    "ResultModel",
    "ShiftDateCell",
    "SolveRequest",
    "SolveRequestStatus",
    "SolveScope",
    "SolveScopeType",
    "SolverOutputMetadata",
    "SolverOutputStatus",
    "SolveTaskStatus",
    "SQSSolveMessage",
    "SQSSolveQueueMessage",
    "WorkerDateCell",
    "TeamGenerationSettings",
    "TeamWithMembership",
    "Team",
    "MembershipForTeamWithMembership",
    "EnrichedTeamInvitation",
    "TeamInvitation",
    "TeamInvitationStatus",
    "TeamInvitationType",
    "INVITE_TYPE_ROLE_MAP",
    "TEAM_ROLE_TO_AUTHZ_ROLE",
    "TeamMembership",
    "TeamMembershipRole",
    "Language",
    "PasswordData",
    "SystemRole",
    "User",
    "UserWithMembership",
    "Worker",
    "WorkerDates",
]
