from shared.schemas.core.assignment import (
    Assignment,
    AssignmentSource,
    AssignmentsRecurrencesResult,
)
from shared.schemas.core.attribute import Attribute, AttributeOwnerType
from shared.schemas.core.breach import Breach, ObjectiveCategory, Variable
from shared.schemas.core.config import Config
from shared.schemas.core.constraint import (
    Block,
    BlockNameOptions,
    BlockTypeOptions,
    ConfigurationConstraintPenalty,
    Constraint,
    ConstraintBuild,
    ConstraintBuildAugmented,
    ConstraintFai,
    ConstraintFil,
    ConstraintOperator,
    ConstraintOrd,
    Constraints,
    ConstraintSeq,
    ConstraintSum,
    ConstraintType,
    CoveragePenalty,
    MissingAttribute,
    Penalties,
    Penalty,
    ShiftWorkerOption,
    SWOIdTypes,
    SystemConstraintPenalty,
    Template,
    TemplateBlock,
    UserConstraintPenalty,
    VarDaySelectorOptions,
    VarShiftSelectorOptions,
    VarWorkerSelectorOptions,
)
from shared.schemas.core.coverage import Coverage
from shared.schemas.core.coverage_selector import CoverageSelector
from shared.schemas.core.daily_shift_demand import (
    DailyShiftDemand,
    DeleteDailyShiftDemandRequest,
    DemandsResult,
    DSDSourceType,
)
from shared.schemas.core.dim_entry import DimEntry
from shared.schemas.core.dimension import (
    Dimension,
    DimensionAndDimEntries,
    DimensionEntryType,
    DimensionType,
    NewDimension,
)
from shared.schemas.core.engine import (
    ConfigurationConstraints,
    CustomSolverParams,
    EngineInputs,
    EngineInputsAugmented,
    EngineOutputs,
    EngineOutputsAugmented,
    ModelConfig,
    ModelSetup,
    SolverParams,
    SolveStrategy,
    SystemConstraints,
)
from shared.schemas.core.export_options import (
    ExportOptions,
    ExportPeriodOptions,
)
from shared.schemas.core.link_shift import LinkShift, LSChange
from shared.schemas.core.model_output import ModelOutput, ModelOutputStatus
from shared.schemas.core.recurrence import (
    FrequencyType,
    MonthRepeatType,
    OccurrenceInfo,
    OccurrenceType,
    RecurrenceEndType,
    RecurrenceExclusion,
    RecurrenceRule,
    RecurrenceUpdateScope,
)
from shared.schemas.core.request import (
    FulfillmentStatus,
    Request,
    RequestAugmented,
    RequestStatus,
    RequestType,
)
from shared.schemas.core.schedule import (
    DuplicateOptions,
    DuplicateRequest,
    DuplicateResult,
    Period,
    QuickStaffing,
    Schedule,
    ScheduleSolveStatus,
    ScheduleStatus,
    Solution,
    SolveDetails,
    SolveDetailsStatus,
    WorkTimeTable,
    WorkTimeTableData,
)
from shared.schemas.core.shift import (
    Shift,
    ShiftLeaveType,
    ShiftRestType,
    ShiftType,
    Staffing,
)
from shared.schemas.core.shift_demand import ShiftDemand
from shared.schemas.core.shift_demand_exclusion import ShiftDemandExclusion
from shared.schemas.core.shift_demand_new import (
    ShiftDemandNew,
    ShiftDemandSource,
)
from shared.schemas.core.shift_demand_template import (
    ShiftDemandTemplate,
    TemplateType,
    TemplateWeekData,
    create_template_from_demands,
)
from shared.schemas.core.specialty import Specialty
from shared.schemas.core.stats import (
    HeaderUnitOptions,
    Stats,
    StatsHeader,
    StatsOptions,
    StatsTimeFrameOptions,
    StatsUnitOptions,
    StatsValue,
)
from shared.schemas.core.task import TaskServices
from shared.schemas.core.team import (
    MembershipForTeamWithMembership,
    Team,
    TeamWithMembership,
)
from shared.schemas.core.team_invitation import (
    EnrichedTeamInvitation,
    TeamInvitation,
    TeamInvitationStatus,
    TeamInvitationType,
)
from shared.schemas.core.team_membership import (
    INVITE_TYPE_ROLE_MAP,
    TEAM_ROLE_TO_AUTHZ_ROLE,
    TeamMembership,
    TeamMembershipRole,
)
from shared.schemas.core.user import (
    Language,
    PasswordData,
    User,
    UserAuth,
    UserDashboard,
    UserWithMembership,
)
from shared.schemas.core.worker import Worker, WorkerDates

# pylint: disable=R0801
__all__ = [
    "Attribute",
    "AssignmentSource",
    "AssignmentsRecurrencesResult",
    "AttributeOwnerType",
    "Config",
    "Assignment",
    "Block",
    "BlockNameOptions",
    "BlockTypeOptions",
    "ConfigurationConstraintPenalty",
    "Constraint",
    "ConstraintBuild",
    "ConstraintBuildAugmented",
    "ConstraintFai",
    "ConstraintFil",
    "ConstraintOperator",
    "ConstraintOrd",
    "Constraints",
    "ConstraintSeq",
    "ConstraintSum",
    "ConstraintType",
    "CoveragePenalty",
    "MissingAttribute",
    "Penalties",
    "Penalty",
    "ShiftWorkerOption",
    "SWOIdTypes",
    "SystemConstraintPenalty",
    "Template",
    "TemplateBlock",
    "UserConstraintPenalty",
    "VarDaySelectorOptions",
    "VarShiftSelectorOptions",
    "VarWorkerSelectorOptions",
    "Coverage",
    "CoverageSelector",
    "DailyShiftDemand",
    "DeleteDailyShiftDemandRequest",
    "DemandsResult",
    "DSDSourceType",
    "ShiftDemand",
    "ShiftDemandExclusion",
    "ShiftDemandNew",
    "ShiftDemandSource",
    "ShiftDemandTemplate",
    "TemplateType",
    "TemplateWeekData",
    "create_template_from_demands",
    "Dimension",
    "DimensionAndDimEntries",
    "DimensionEntryType",
    "DimensionType",
    "NewDimension",
    "DimEntry",
    "ConfigurationConstraints",
    "CustomSolverParams",
    "EngineInputs",
    "EngineInputsAugmented",
    "EngineOutputs",
    "EngineOutputsAugmented",
    "ModelConfig",
    "ModelSetup",
    "SolverParams",
    "SolveStrategy",
    "SystemConstraints",
    "ExportOptions",
    "ExportPeriodOptions",
    "ModelOutput",
    "ModelOutputStatus",
    "FrequencyType",
    "MonthRepeatType",
    "OccurrenceInfo",
    "RecurrenceEndType",
    "RecurrenceExclusion",
    "RecurrenceRule",
    "OccurrenceType",
    "RecurrenceUpdateScope",
    "FulfillmentStatus",
    "Request",
    "RequestAugmented",
    "RequestStatus",
    "RequestType",
    "Breach",
    "ObjectiveCategory",
    "DuplicateOptions",
    "DuplicateRequest",
    "DuplicateResult",
    "Period",
    "QuickStaffing",
    "Schedule",
    "SolveDetailsStatus",
    "ScheduleSolveStatus",
    "ScheduleStatus",
    "Solution",
    "SolveDetails",
    "Variable",
    "WorkTimeTable",
    "WorkTimeTableData",
    "LinkShift",
    "LSChange",
    "Shift",
    "ShiftLeaveType",
    "ShiftRestType",
    "ShiftType",
    "Staffing",
    "HeaderUnitOptions",
    "StatsOptions",
    "StatsTimeFrameOptions",
    "StatsUnitOptions",
    "Stats",
    "StatsHeader",
    "StatsValue",
    "TaskServices",
    "Specialty",
    "TeamWithMembership",
    "Team",
    "MembershipForTeamWithMembership",
    "EnrichedTeamInvitation",
    "TeamInvitation",
    "TeamInvitationStatus",
    "TeamInvitationType",
    "INVITE_TYPE_ROLE_MAP",
    "TEAM_ROLE_TO_AUTHZ_ROLE",
    "TeamMembership",
    "TeamMembershipRole",
    "Language",
    "PasswordData",
    "User",
    "UserAuth",
    "UserDashboard",
    "UserWithMembership",
    "Worker",
    "WorkerDates",
]
