version: '3.8'

services:
  backend:
    build: 
      context: "./backend"
    env_file:
      - .env.local
    ports:
      - "4000:4000"
  
  permit-pdp:
    image: permitio/pdp-v2:latest
    env_file:
      - .env.local
    # environment:
    #   - PDP_API_KEY=${PDP_API_KEY}
    ports:
      - "8181:8181"
      - "7766:7000"

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb:/data/db
  #     - mongodb_config:/data/configdb

  frontend:
    build: 
      context: "./frontend"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL="http://0.0.0.0:4000"
      - NEXT_PUBLIC_CLIENT_URL="http://0.0.0.0:3000"

# volumes:
#   mongodb:
#   mongodb_config:
