services:
  backend:
    build: 
      context: "./backend"
    env_file:
      - .env.local
    ports:
      - "4000:4000"
  
  permit-pdp:
    image: permitio/pdp-v2:latest
    env_file:
      - .env.local
    ports:
      - "8181:8181"
      - "7766:7000"


  new-frontend:
    build: 
      context: "./new_frontend"
      args:
        API_URL: "http://localhost:4000"
        CLIENT_URL: "http://localhost:3000"
    ports:
      - "3000:3000"


