services:
  # MongoDB Database
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    healthcheck:
      test: mongo --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

  # LocalStack (to emulate SQS)
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    # environment:
    #   - SERVICES=sqs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localstack:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cerbos AuthZ
  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    container_name: cerbos
    ports:
      - "3592:3592"  # gRPC
      - "3593:3593"  # HTTP / playground
    volumes:
      - ./cerbos-policies:/policies:ro
    command: server --config=/policies/.cerbos.yaml
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://cerbos:3593/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
    driver: local