"""Strict schemas for the Plan-and-Execute copilot pipeline.

The Planner sub-agent outputs an ``ExecutionPlan`` JSON DAG. The Executor
walks it deterministically, resolving ``$VARIABLE`` placeholders from prior
step outputs before invoking each tool.
"""

import re
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator

_VARIABLE_PATTERN = re.compile(r"^\$[A-Z_][A-Z0-9_]*$")


class PlanStepStatus(str, Enum):
    COMPLETED = "completed"
    PENDING_CONFIRMATION = "pending_confirmation"
    WAITING = "waiting"


class PlanStep(BaseModel):
    """A single step in an execution plan.

    ``args`` may contain string values that start with ``$`` — these are
    variable placeholders that the Executor resolves from prior step outputs
    before invoking the tool.
    """

    step: int = Field(..., ge=1, description="1-indexed step number in the plan.")
    tool: str = Field(..., description="Tool name from the shared TOOL_REGISTRY.")
    args: dict[str, Any] = Field(
        default_factory=dict,
        description="Tool arguments; string values starting with $ are variable "
        "placeholders resolved by the Executor from prior step outputs.",
    )
    assign_output_to: str | None = Field(
        None,
        description="$VARIABLE name to bind this step's output to, e.g. $TARGET_DATE.",
    )
    extract_key: str | None = Field(
        None,
        description="Top-level key in the tool's output dict to extract and "
        "bind to assign_output_to, e.g. 'calculated_date' or 'worker_id'.",
    )
    description: str = Field(
        ..., description="Human-readable step description for the UI checklist."
    )

    @field_validator("assign_output_to")
    @classmethod
    def must_be_variable(cls, v: str | None) -> str | None:
        if v is not None and not _VARIABLE_PATTERN.match(v):
            raise ValueError(
                f"assign_output_to must be a $VARIABLE (e.g. $TARGET_DATE), got {v!r}"
            )
        return v


class ExecutionPlan(BaseModel):
    """A static, sequential checklist generated by the Planner.

    The Executor walks ``plan`` in order. Read-side steps run eagerly and
    their outputs are bound to ``$VARIABLE`` names. The executor stops at
    the first confirmation-requiring step and returns a ``PendingAction``.
    """

    complexity: str = Field(
        default="high",
        description="Complexity tier: 'low' (use ReAct bypass) or 'high'.",
    )
    summary: str = Field(
        ..., description="One-line summary of the plan for the UI heading."
    )
    plan: list[PlanStep] = Field(
        ..., min_length=1, description="Ordered list of steps to execute."
    )

    @field_validator("plan")
    @classmethod
    def steps_must_be_sequential(cls, v: list[PlanStep]) -> list[PlanStep]:
        for i, s in enumerate(v, start=1):
            if s.step != i:
                raise ValueError(
                    f"Plan steps must be sequential 1..N; step {i} has step={s.step}"
                )
        return v


class CompletedStep(BaseModel):
    """Status of a single step after execution."""

    step: int
    status: PlanStepStatus


class PlanExecutionResult(BaseModel):
    """Result of executing (part of) an ExecutionPlan."""

    plan: ExecutionPlan
    completed_steps: list[CompletedStep]
    pending_actions: list[dict[str, Any]] = Field(default_factory=list)
    execution_memory: dict[str, Any] = Field(default_factory=dict)
