[tool.poetry]
name = "nsp-pro"
version = "0.1.0"
description = ""
authors = ["FelipeKha <felipe.kharaba@icloud.com>"]
readme = "README.md"
packages = [{include = "nsp_pro"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
ortools = "^9.6.2534"
flask = "^2.3.2"
pymongo = "^4.3.3"
mongoengine = "^0.27.0"
mypy = "^1.2.0"
flake8 = "^6.0.0"
pylint = "^2.17.3"
mongo-types = "^0.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
