from datetime import date, timedelta
from typing import List, Optional, Tuple

from shared.schemas.core import (
    Assignment,
    AssignmentsRecurrencesResult,
    RecurrenceEndType,
    RecurrenceExclusion,
    RecurrenceRule,
    RecurrenceUpdateScope,
    Shift,
    ShiftType,
)

from src.services.base_service import BaseService
from src.utils.recurrence_utils import generate_recurring_dates


class AssignmentService(BaseService):
    def create_assignment_and_recurrence(
        self,
        assignment_new: Assignment,
        recurrence_rule: Optional[RecurrenceRule] = None,
    ) -> AssignmentsRecurrencesResult:
        out_assignments: List[Assignment] = []
        assignment_recup = None

        assignment_saved, shift = self._create_main_assignment(
            assignment=assignment_new
        )
        out_assignments.append(assignment_saved)

        if shift.shift_type == ShiftType.DUTY:
            assignment_recup = self._create_recuperation_assignment(
                assignment_duty=assignment_saved
            )
            if assignment_recup:
                out_assignments.append(assignment_recup)

        recurrence_created: Optional[RecurrenceRule] = None
        if recurrence_rule is not None:
            recurrence_created, assignments_recurrence = (
                self._handle_recurrence_creation(
                    recurrence_rule=recurrence_rule,
                    assignment=assignment_saved,
                    assignment_recup=assignment_recup,
                )
            )
            out_assignments.extend(assignments_recurrence)
        return AssignmentsRecurrencesResult(
            assignments_created=out_assignments,
            assignments_read=[],
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=recurrence_created,
            recurrences_read=[],
            recurrence_updated=None,
        )

    def _create_main_assignment(
        self, assignment: Assignment
    ) -> Tuple[Assignment, Shift]:
        shift = self.collection.shift_db.get_shift_by_id(assignment.shift_id)
        if shift is None:
            raise ValueError(f"Shift with ID {assignment.shift_id} does not exist.")
        return (
            self.collection.assignment_db.create_assignment(assignment),
            shift,
        )

    def _create_recuperation_assignment(
        self, assignment_duty: Assignment
    ) -> Optional[Assignment]:
        shift_recup = self.collection.shift_db.get_recuperation_shift(
            shift_id=assignment_duty.shift_id
        )
        if shift_recup is not None:
            assignment_recup = Assignment(
                id="",  # ID will be generated by the database
                team_id=assignment_duty.team_id,
                schedule_id=assignment_duty.schedule_id,
                worker_id=assignment_duty.worker_id,
                date=assignment_duty.date,
                shift_id=shift_recup.id,
                fixed=assignment_duty.fixed,
                reference_assignment_id=assignment_duty.id,
            )
            return self.collection.assignment_db.create_assignment(assignment_recup)
        return None

    def _handle_recurrence_creation(
        self,
        recurrence_rule: RecurrenceRule,
        assignment: Assignment,
        assignment_recup: Optional[Assignment] = None,
    ) -> Tuple[RecurrenceRule, List[Assignment]]:
        recurrence_rule.assignment_id = assignment.id
        recurrence_rule_saved = self.collection.recurrence_db.create_recurrence(
            recurrence_rule
        )
        assignments_recurrence = self._handle_recurrence_assignments_creation(
            recurrence=recurrence_rule_saved,
            assignment=assignment,
            assignment_recup=assignment_recup,
        )
        return (recurrence_rule_saved, assignments_recurrence)

    def _handle_recurrence_assignments_creation(
        self,
        recurrence: RecurrenceRule,
        assignment: Assignment,
        assignment_recup: Optional[Assignment] = None,
    ) -> List[Assignment]:
        assignment.recurrence_rule_id = recurrence.id
        if assignment_recup:
            assignment_recup.recurrence_rule_id = recurrence.id

        assignments_recurrence = (
            self.collection.assignment_db.update_assignments(
                [assignment, assignment_recup]
            )
            if assignment_recup
            else [self.collection.assignment_db.update_assignment(assignment)]
        )

        schedule_wip = self.collection.schedule_db.get_schedule_campaign(
            team_id=assignment.team_id
        )
        if schedule_wip:
            dates_recurring = generate_recurring_dates(
                period_start=schedule_wip.start_date,
                period_end=schedule_wip.end_date,
                recurrence_rule=recurrence,
                exclusions=[],
            )
            assignments_rec_campaign = [
                Assignment(
                    id="",  # ID will be generated by the database
                    team_id=assignment.team_id,
                    schedule_id=assignment.schedule_id,
                    worker_id=assignment.worker_id,
                    date=date,
                    shift_id=assignment.shift_id,
                    fixed=assignment.fixed,
                    reference_assignment_id=None,
                    recurrence_rule_id=recurrence.id,
                )
                for date in dates_recurring
                if date != assignment.date
            ] + [
                Assignment(
                    id="",  # ID will be generated by the database
                    team_id=assignment_recup.team_id,
                    schedule_id=assignment_recup.schedule_id,
                    worker_id=assignment_recup.worker_id,
                    date=assignment_recup.date,
                    shift_id=assignment_recup.shift_id,
                    fixed=assignment_recup.fixed,
                    reference_assignment_id=assignment.id,
                    recurrence_rule_id=recurrence.id,
                )
                for date in dates_recurring
                if assignment_recup
                if date != assignment_recup.date
            ]
            assignments_recurrence.extend(
                self.collection.assignment_db.create_assignments(
                    assignments_rec_campaign
                )
            )
        return assignments_recurrence

    def create_recuperation_assignments_upon_shift_duty_creation(
        self, shift_duty_id: str, shift_recup_id: str, team_id: str
    ) -> None:
        # fmt: off
        assignments_duty_recup = self.collection.assignment_db\
            .get_assignments_by_team_and_shifts_today_onward(
                team_id=team_id,
                shift_ids=[shift_duty_id, shift_recup_id],
            )
        # fmt: on

        # Separate assignments by shift
        assignments_duty = [
            assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_duty_id
        ]
        assignments_recup_dict = {
            (assignment.worker_id, assignment.date): assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_recup_id
        }

        # Create recuperation assignments if not already existing
        new_assignments = []
        for duty_assignment in assignments_duty:
            key = (duty_assignment.worker_id, duty_assignment.date)
            if key not in assignments_recup_dict:
                new_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=duty_assignment.team_id,
                    schedule_id=duty_assignment.schedule_id,
                    worker_id=duty_assignment.worker_id,
                    date=duty_assignment.date,  # Adjust date if needed
                    shift_id=shift_recup_id,
                    fixed=duty_assignment.fixed,
                    reference_assignment_id=duty_assignment.id,
                )
                new_assignments.append(new_assignment)

        if new_assignments:
            self.collection.assignment_db.create_assignments(new_assignments)

    def get_assignments_and_recurrences(
        self,
        team_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> AssignmentsRecurrencesResult:
        if start_date is None or end_date is None:
            assignments = self.collection.assignment_db.get_assignments(team_id)
        else:
            assignments = self.collection.assignment_db.get_assignments_by_dates(
                team_id, start_date, end_date
            )
        recurrences = self.collection.recurrence_db.get_recurrences_by_team_id(
            team_id=team_id
        )
        return AssignmentsRecurrencesResult(
            assignments_created=[],
            assignments_read=assignments,
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=None,
            recurrences_read=recurrences,
            recurrence_updated=None,
        )

    def update_assignment_and_recurrence(
        self,
        assignment_new: Assignment,
        recurrence_update_scope: Optional[RecurrenceUpdateScope] = None,
        recurrence: Optional[RecurrenceRule] = None,
    ) -> AssignmentsRecurrencesResult:
        assignment_updated, assignment_old = self._update_main_assignment(
            assignment_new=assignment_new,
            recurrence_update_scope=recurrence_update_scope,
        )
        (
            assignments_recup_created,
            assignments_recup_updated,
            assignments_recup_deleted_ids,
        ) = self._udpdate_recup_assignments(
            assignment_new=assignment_new, assignment_old=assignment_old
        )
        if recurrence_update_scope and recurrence:
            ar_result_rec_update = self._handle_recurrence_update(
                recurrence_update_scope=recurrence_update_scope,
                recurrence_rule=recurrence,
                assignment=assignment_updated,
                assignment_recup=(
                    assignments_recup_created[0]
                    if assignments_recup_created
                    else (
                        assignments_recup_updated[0]
                        if assignments_recup_updated
                        else None
                    )
                ),
            )
            ar_result_rec_update.assignments_created.extend(assignments_recup_created)
            ar_result_rec_update.assignments_updated.extend(
                [assignment_updated] + assignments_recup_updated
            )
            ar_result_rec_update.assignments_deleted_ids.extend(
                assignments_recup_deleted_ids
            )
            return ar_result_rec_update
        return AssignmentsRecurrencesResult(
            assignments_created=assignments_recup_created,
            assignments_read=[],
            assignments_updated=[assignment_updated] + assignments_recup_updated,
            assignments_deleted_ids=assignments_recup_deleted_ids,
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
        )

    def _update_main_assignment(
        self,
        assignment_new: Assignment,
        recurrence_update_scope: Optional[RecurrenceUpdateScope] = None,
    ) -> Tuple[Assignment, Assignment]:
        assignment_old = self.collection.assignment_db.get_assignment_by_id(
            assignment_new.id
        )
        if not assignment_old:
            raise ValueError(f"Assignment with ID {assignment_new.id} does not exist.")
        if recurrence_update_scope and recurrence_update_scope in [
            RecurrenceUpdateScope.SINGLE,
            RecurrenceUpdateScope.FUTURE,
        ]:
            assignment_new.recurrence_rule_id = None
        assignment_updated = self.collection.assignment_db.update_assignment(
            assignment=assignment_new
        )
        return assignment_updated, assignment_old

    def _udpdate_recup_assignments(
        self, assignment_new: Assignment, assignment_old: Assignment
    ) -> Tuple[List[Assignment], List[Assignment], List[str]]:
        assignments_recup_created: List[Assignment] = []
        assignments_recup_updated: List[Assignment] = []
        assignments_recup_deleted_ids: List[str] = []
        if assignment_old.shift_id == assignment_new.shift_id:
            if assignment_old.fixed != assignment_new.fixed:
                assignment_recup_old = (
                    self.collection.assignment_db.get_assignments_by_reference_id(
                        reference_id=assignment_old.id
                    )
                )
                for assignment in assignment_recup_old:
                    assignment.fixed = assignment_new.fixed
                    assignments_recup_updated.append(
                        self.collection.assignment_db.update_assignment(assignment)
                    )
            return (
                assignments_recup_created,
                assignments_recup_updated,
                assignments_recup_deleted_ids,
            )

        # Check if the shift type is changing
        shift_old = self.collection.shift_db.get_shift_by_id(assignment_old.shift_id)
        shift_new = self.collection.shift_db.get_shift_by_id(assignment_new.shift_id)

        if not shift_old or not shift_new:
            raise ValueError("Invalid shift ID provided.")

        if shift_old.shift_type == ShiftType.DUTY:
            assignments_recup_deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_reference_id(
                    reference_id=assignment_old.id
                )
            )

        if shift_new.shift_type == ShiftType.DUTY:
            shift_recup_new = self.collection.shift_db.get_recuperation_shift(
                shift_id=assignment_new.shift_id
            )
            if shift_recup_new:
                recuperation_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=assignment_new.team_id,
                    schedule_id=assignment_new.schedule_id,
                    worker_id=assignment_new.worker_id,
                    date=assignment_new.date,
                    shift_id=shift_recup_new.id,
                    fixed=assignment_new.fixed,
                    reference_assignment_id=assignment_new.id,
                )
                assignments_recup_created.append(
                    self.collection.assignment_db.create_assignment(
                        recuperation_assignment
                    )
                )
        return (
            assignments_recup_created,
            assignments_recup_updated,
            assignments_recup_deleted_ids,
        )

    def _handle_recurrence_update(
        self,
        recurrence_update_scope: RecurrenceUpdateScope,
        recurrence_rule: RecurrenceRule,
        assignment: Assignment,
        assignment_recup: Optional[Assignment] = None,
    ) -> AssignmentsRecurrencesResult:
        if recurrence_update_scope == RecurrenceUpdateScope.NONE:
            recurrence_created, assignments_recurrence = (
                self._handle_recurrence_creation(
                    recurrence_rule=recurrence_rule,
                    assignment=assignment,
                    assignment_recup=assignment_recup,
                )
            )
            return AssignmentsRecurrencesResult(
                assignments_created=assignments_recurrence,
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=[],
                recurrence_created=recurrence_created,
                recurrences_read=[],
                recurrence_updated=None,
            )
        if recurrence_update_scope == RecurrenceUpdateScope.SINGLE:
            # Update single assignment (done outside of this method) and create
            # recurrence exception
            exclusion = RecurrenceExclusion(
                id="",  # ID will be generated by the database
                recurrence_rule_id=recurrence_rule.id,
                excluded_date=assignment.date,
            )
            self.collection.recurrence_exclusion_db.create_recurrence_exclusion(
                exclusion
            )
            # TODO_: find solution in case we are changing the only assignment
            # for this recurrence
            return AssignmentsRecurrencesResult(
                assignments_created=[],
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=[],
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=None,
            )
        if recurrence_update_scope == RecurrenceUpdateScope.FUTURE:
            # Create new recurrence starting at the time of the assignment
            recurrence_new = RecurrenceRule(
                id="",  # ID will be generated by the database
                team_id=recurrence_rule.team_id,
                recurrence_type=recurrence_rule.recurrence_type,
                assignment_id=assignment.id,
                daily_shift_demand_id=recurrence_rule.daily_shift_demand_id,
                repeat_every=recurrence_rule.repeat_every,
                frequency_type=recurrence_rule.frequency_type,
                week_days=recurrence_rule.week_days,
                month_repeat_type=recurrence_rule.month_repeat_type,
                recurrence_end_type=recurrence_rule.recurrence_end_type,
                start_date=assignment.date,
                end_date=recurrence_rule.end_date,
                number_of_occurrences=recurrence_rule.number_of_occurrences,
            )
            # Update recurrence to end at date of assignment
            recurrence_rule.recurrence_end_type = RecurrenceEndType.END_DATE
            recurrence_rule.end_date = assignment.date + timedelta(days=-1)
            recurrence_updated = self.collection.recurrence_db.update_recurrence(
                recurrence_rule
            )
            # Delete all future assignments for this recurrence
            # fmt: off
            deleted_assignments_ids = self.collection.assignment_db\
                .delete_assignments_by_recurrence_rule_id_from_date(
                    recurrence_rule_id=recurrence_rule.id,
                    from_date=assignment.date,
                )
            # fmt: on
            # Create new assignments for the new recurrence
            recurrence_new, assignments_recurrence = self._handle_recurrence_creation(
                recurrence_rule=recurrence_new,
                assignment=assignment,
                assignment_recup=assignment_recup,
            )
            return AssignmentsRecurrencesResult(
                assignments_created=assignments_recurrence,
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=deleted_assignments_ids,
                recurrence_created=recurrence_new,
                recurrences_read=[],
                recurrence_updated=recurrence_updated,
            )
        if recurrence_update_scope == RecurrenceUpdateScope.ALL:
            # Update the recurrence
            recurrence_rule.assignment_id = assignment.id
            recurrence_updated = self.collection.recurrence_db.update_recurrence(
                recurrence_rule
            )
            # Update all assignments for this recurrence (delete and create)
            assignments_deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_recurrence_rule_id(
                    recurrence_rule_id=recurrence_updated.id
                )
            )
            assignments_recurrence = self._handle_recurrence_assignments_creation(
                recurrence=recurrence_updated,
                assignment=assignment,
                assignment_recup=assignment_recup,
            )
            return AssignmentsRecurrencesResult(
                assignments_created=assignments_recurrence,
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=assignments_deleted_ids,
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=recurrence_updated,
            )
        raise ValueError(f"Invalid recurrence update scope: {recurrence_update_scope}")

    def delete_assignment(self, assignment_id: str) -> List[str]:
        deleted_ids = self.collection.assignment_db.delete_assignments_by_reference_id(
            reference_id=assignment_id
        )
        deleted_ids.append(assignment_id)
        self.collection.assignment_db.delete_assignment(assignment_id)
        return deleted_ids
