from typing import Dict, List, Optional

from shared.schemas.core import Assignment, RecurrenceRule, ShiftType

from src.services.base_service import BaseService


class AssignmentService(BaseService):
    def create_assignment(
        self,
        assignment_new: Assignment,
        recurrence_rule: Optional[RecurrenceRule] = None,
    ) -> Dict[str, List[Assignment] | Optional[RecurrenceRule]]:
        out_assignments: List[Assignment] = []
        out_recurrence_rule: Optional[RecurrenceRule] = None

        shift = self.collection.shift_db.get_shift_by_id(assignment_new.shift_id)
        if shift is None:
            raise ValueError(f"Shift with ID {assignment_new.shift_id} does not exist.")
        assignment_saved = self.collection.assignment_db.create_assignment(
            assignment_new
        )
        out_assignments.append(assignment_saved)

        shift_recup = None
        if shift.shift_type == ShiftType.DUTY:
            shift_recup = self.collection.shift_db.get_recuperation_shift(
                shift_id=assignment_new.shift_id
            )
        if shift_recup is not None:
            assignment_recup = Assignment(
                id="",  # ID will be generated by the database
                team_id=assignment_new.team_id,
                schedule_id=assignment_new.schedule_id,
                worker_id=assignment_new.worker_id,
                date=assignment_new.date,
                shift_id=shift_recup.id,
                fixed=assignment_new.fixed,
                reference_assignment_id=assignment_saved.id,
            )
            assignment_recup_saved = self.collection.assignment_db.create_assignment(
                assignment_recup
            )
            out_assignments.append(assignment_recup_saved)

        if recurrence_rule is not None:
            recurrence_rule.assignment_id = assignment_saved.id
            recurrence_rule_saved = self.collection.recurrence_db.create_recurrence(
                recurrence_rule
            )
            out_recurrence_rule = recurrence_rule_saved
        return {
            "assignments": out_assignments,
            "recurrence_rule": out_recurrence_rule,
        }

    def create_recuperation_assignments(
        self, shift_duty_id: str, shift_recup_id: str, team_id: str
    ) -> None:
        # fmt: off
        assignments_duty_recup = self.collection.assignment_db\
            .get_assignments_by_team_and_shifts_today_onward(
                team_id=team_id,
                shift_ids=[shift_duty_id, shift_recup_id],
            )
        # fmt: on

        # Separate assignments by shift
        assignments_duty = [
            assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_duty_id
        ]
        assignments_recup_dict = {
            (assignment.worker_id, assignment.date): assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_recup_id
        }

        # Create recuperation assignments if not already existing
        new_assignments = []
        for duty_assignment in assignments_duty:
            key = (duty_assignment.worker_id, duty_assignment.date)
            if key not in assignments_recup_dict:
                new_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=duty_assignment.team_id,
                    schedule_id=duty_assignment.schedule_id,
                    worker_id=duty_assignment.worker_id,
                    date=duty_assignment.date,  # Adjust date if needed
                    shift_id=shift_recup_id,
                    fixed=duty_assignment.fixed,
                    reference_assignment_id=duty_assignment.id,
                )
                new_assignments.append(new_assignment)

        if new_assignments:
            self.collection.assignment_db.create_assignments(new_assignments)

    def update_assignment(self, assignment_new: Assignment) -> dict:
        deleted_ids: List[str] = []
        recuperation_assignments: List[Assignment] = []

        assignment_old = self.collection.assignment_db.get_assignment_by_id(
            assignment_new.id
        )
        if not assignment_old:
            raise ValueError(f"Assignment with ID {assignment_new.id} does not exist.")
        if assignment_old.shift_id == assignment_new.shift_id:
            if assignment_old.fixed != assignment_new.fixed:
                assignment_recup_old = (
                    self.collection.assignment_db.get_assignments_by_reference_id(
                        reference_id=assignment_old.id
                    )
                )
                if assignment_recup_old:
                    for assignment in assignment_recup_old:
                        assignment.fixed = assignment_new.fixed
                        recuperation_assignments.append(
                            self.collection.assignment_db.update_assignment(assignment)
                        )
            updated_assignment = self.collection.assignment_db.update_assignment(
                assignment_new
            )
            return {
                "updated_assignment": updated_assignment,
                "recuperation_assignments": recuperation_assignments,
                "deleted_ids": deleted_ids,
            }

        # Check if the shift type is changing
        shift_old = self.collection.shift_db.get_shift_by_id(assignment_old.shift_id)
        shift_new = self.collection.shift_db.get_shift_by_id(assignment_new.shift_id)

        if not shift_old or not shift_new:
            raise ValueError("Invalid shift ID provided.")

        if shift_old.shift_type == ShiftType.DUTY:
            deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_reference_id(
                    reference_id=assignment_old.id
                )
            )

        if shift_new.shift_type == ShiftType.DUTY:
            shift_recup_new = self.collection.shift_db.get_recuperation_shift(
                shift_id=assignment_new.shift_id
            )
            if shift_recup_new:
                recuperation_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=assignment_new.team_id,
                    schedule_id=assignment_new.schedule_id,
                    worker_id=assignment_new.worker_id,
                    date=assignment_new.date,
                    shift_id=shift_recup_new.id,
                    fixed=assignment_new.fixed,
                    reference_assignment_id=assignment_new.id,
                )
                recuperation_assignments.append(
                    self.collection.assignment_db.create_assignment(
                        recuperation_assignment
                    )
                )

        # Update the main assignment
        updated_assignment = self.collection.assignment_db.update_assignment(
            assignment_new
        )

        return {
            "updated_assignment": updated_assignment,
            "recuperation_assignments": recuperation_assignments,
            "deleted_ids": deleted_ids,
        }

    def delete_assignment(self, assignment_id: str) -> List[str]:
        deleted_ids = self.collection.assignment_db.delete_assignments_by_reference_id(
            reference_id=assignment_id
        )
        deleted_ids.append(assignment_id)
        self.collection.assignment_db.delete_assignment(assignment_id)
        return deleted_ids
