from datetime import date, timedelta
from typing import Dict, List, Optional, Set, Tuple

from shared.schemas.core import (
    Assignment,
    AssignmentSource,
    AssignmentsRecurrencesResult,
    DuplicateRequest,
    OccurrenceInfo,
    RecurrenceEndType,
    RecurrenceExclusion,
    RecurrenceRule,
    RecurrenceUpdateScope,
    Schedule,
    ScheduleStatus,
    Shift,
    ShiftType,
)

from src.services.base_service import BaseService
from src.utils.date_utils import build_dates_list
from src.utils.duplicate_utils import (
    build_duplicate_date_mapping,
    validate_duplicate_lists,
)
from src.utils.recurrence_utils import generate_recurring_dates


# pylint: disable=too-many-lines
class AssignmentService(BaseService):
    def create_assignment_and_recurrence(
        self,
        assignment_new: Assignment,
        recurrence_new: Optional[RecurrenceRule] = None,
    ) -> AssignmentsRecurrencesResult:
        shift = self.collection.shift_db.get_shift_by_id(assignment_new.shift_id)
        if shift is None:
            raise ValueError(f"Shift with ID {assignment_new.shift_id} does not exist.")
        if recurrence_new:
            return self._handle_recurrence_and_assignments_creation(
                recurrence=recurrence_new,
                assignment=assignment_new,
                shift=shift,
            )

        out = AssignmentsRecurrencesResult(
            assignments_created=[],
            assignments_read=[],
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )

        assignment_saved = self.collection.assignment_db.create_assignment(
            assignment_new
        )
        out.assignments_created.append(assignment_saved)

        if shift.shift_type == ShiftType.DUTY:
            shifts_recup = self._get_recup_shifts(
                shift_ids=[a.shift_id for a in out.assignments_created]
            )
            assignments_recup = self._create_recuperation_assignments(
                assignments_duty=out.assignments_created,
                shifts_recup=shifts_recup,
            )
            if assignments_recup:
                assignments_recup_saved = (
                    self.collection.assignment_db.create_assignments(assignments_recup)
                )
                out.assignments_created.extend(assignments_recup_saved)
        return out

    def _create_recuperation_assignments(
        self, assignments_duty: List[Assignment], shifts_recup: List[Shift]
    ) -> List[Assignment]:
        duty_to_recup_map = self._build_duty_id_to_recup_shift_map(
            shifts_recup=shifts_recup
        )
        assignments_recup = []
        for assignment in assignments_duty:
            if assignment.shift_id in duty_to_recup_map:
                assignments_recup.append(
                    Assignment(
                        id="",  # ID will be generated by the database
                        team_id=assignment.team_id,
                        schedule_id=assignment.schedule_id,
                        worker_id=assignment.worker_id,
                        date=assignment.date,
                        shift_id=duty_to_recup_map[assignment.shift_id],
                        fixed=assignment.fixed,
                        source=assignment.source,
                        reference_assignment_id=assignment.id,
                        source_id=assignment.source_id,
                    )
                )
        return assignments_recup

    def _get_recup_shifts(self, shift_ids: List[str]) -> List[Shift]:
        shift_ids = list(set(shift_ids))
        return self.collection.shift_db.get_recuperation_shifts(
            shift_ids=list(shift_ids)
        )

    @staticmethod
    def _build_duty_id_to_recup_shift_map(shifts_recup: List[Shift]) -> dict:
        duty_to_recup_map = {}
        for shift in shifts_recup:
            duty_to_recup_map[shift.recuperation_duty_id] = shift.id

        return duty_to_recup_map

    # pylint: disable=too-many-arguments, too-many-locals
    def _handle_recurrence_and_assignments_creation(
        self,
        recurrence: RecurrenceRule,
        assignment: Assignment,
        shift: Shift,
        create_recurrence: bool = True,
        create_first_assignment: bool = True,
    ) -> AssignmentsRecurrencesResult:
        out = AssignmentsRecurrencesResult(
            assignments_created=[],
            assignments_read=[],
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )
        if create_recurrence:
            recurrence.occurrence_info.worker_id = assignment.worker_id
            recurrence.occurrence_info.shift_id = assignment.shift_id
            recurrence = self.collection.recurrence_db.create_recurrence(recurrence)
            out.recurrence_created = recurrence
        schedule_wip = self.collection.schedule_db.get_schedule_campaign(
            team_id=recurrence.team_id
        )
        assignments_recurrence = []
        if schedule_wip:
            period_dates = build_dates_list(
                start_date=schedule_wip.start_date,
                end_date=schedule_wip.end_date,
            )
            assignments_recurrence = self._handle_recurrence_assignments_creation(
                recurrence=recurrence,
                period_dates=period_dates,
                schedule_id=schedule_wip.id,
                create_first_assignment=create_first_assignment,
            )
            if assignments_recurrence:
                assignments_recurrence_saved = (
                    self.collection.assignment_db.create_assignments(
                        assignments_recurrence
                    )
                )
                out.assignments_created.extend(assignments_recurrence_saved)

        if create_first_assignment:
            existing_assignment = next(
                (
                    a
                    for a in out.assignments_created
                    if a.date == assignment.date
                    and a.worker_id == assignment.worker_id
                    and a.shift_id == assignment.shift_id
                ),
                None,
            )
            if not existing_assignment:
                assignment_saved = self.collection.assignment_db.create_assignment(
                    assignment
                )
                out.assignments_created.append(assignment_saved)

        if shift.shift_type == ShiftType.DUTY:
            shifts_recup = self._get_recup_shifts(
                shift_ids=[a.shift_id for a in out.assignments_created]
            )
            assignments_recup = self._create_recuperation_assignments(
                assignments_duty=out.assignments_created,
                shifts_recup=shifts_recup,
            )
            if assignments_recup:
                assignments_recup_saved = (
                    self.collection.assignment_db.create_assignments(assignments_recup)
                )
                out.assignments_created.extend(assignments_recup_saved)
        return out

    @staticmethod
    def _handle_recurrence_assignments_creation(
        recurrence: RecurrenceRule,
        period_dates: List[date],
        schedule_id: str,
        create_first_assignment: bool = True,
    ) -> List[Assignment]:
        if (
            recurrence.occurrence_info.worker_id is None
            or recurrence.occurrence_info.shift_id is None
        ):
            raise ValueError(
                "Recurrence must have a worker ID and a shift ID to create "
                + "assignments."
            )
        dates_recurring = generate_recurring_dates(
            period_dates=period_dates,
            recurrence_rule=recurrence,
            exclusions=[],
        )
        if not create_first_assignment:
            dates_recurring = [d for d in dates_recurring if d != recurrence.start_date]
        assignments_rec_campaign = [
            Assignment(
                id="",  # ID will be generated by the database
                team_id=recurrence.team_id,
                schedule_id=schedule_id,
                worker_id=recurrence.occurrence_info.worker_id,
                date=date,
                shift_id=recurrence.occurrence_info.shift_id,
                fixed=True,
                source=AssignmentSource.RECURRENCE,
                reference_assignment_id=None,
                source_id=recurrence.id,
            )
            for date in dates_recurring
        ]
        return assignments_rec_campaign

    def create_recuperation_assignments_upon_shift_duty_creation(
        self, shift_duty_id: str, shift_recup_id: str, team_id: str
    ) -> None:
        # fmt: off
        assignments_duty_recup = self.collection.assignment_db\
            .get_assignments_by_team_and_shifts_today_onward(
                team_id=team_id,
                shift_ids=[shift_duty_id, shift_recup_id],
            )
        # fmt: on

        # Separate assignments by shift
        assignments_duty = [
            assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_duty_id
        ]
        assignments_recup_dict = {
            (assignment.worker_id, assignment.date): assignment
            for assignment in assignments_duty_recup
            if assignment.shift_id == shift_recup_id
        }

        # Create recuperation assignments if not already existing
        new_assignments = []
        for duty_assignment in assignments_duty:
            key = (duty_assignment.worker_id, duty_assignment.date)
            if key not in assignments_recup_dict:
                new_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=duty_assignment.team_id,
                    schedule_id=duty_assignment.schedule_id,
                    worker_id=duty_assignment.worker_id,
                    date=duty_assignment.date,  # Adjust date if needed
                    shift_id=shift_recup_id,
                    fixed=duty_assignment.fixed,
                    source=duty_assignment.source,
                    reference_assignment_id=duty_assignment.id,
                )
                new_assignments.append(new_assignment)

        if new_assignments:
            self.collection.assignment_db.create_assignments(new_assignments)

    # pylint: disable=too-many-locals
    def update_assignments_for_schedule_dates_change(
        self, schedule_new: Schedule, schedule_old: Optional[Schedule] = None
    ) -> None:
        dates_new = build_dates_list(
            start_date=schedule_new.start_date,
            end_date=schedule_new.end_date,
        )
        dates_old: List[date] = []
        if schedule_old is not None:
            dates_old = build_dates_list(
                start_date=schedule_old.start_date,
                end_date=schedule_old.end_date,
            )
            # Get dates in old schedule that are not in new schedule
            dates_removed = [d for d in dates_old if d not in dates_new]
            # Delete schedule assignments for dates removed
            self.collection.assignment_db.delete_assignments_by_schedule_id_and_dates(
                schedule_id=schedule_new.id, dates=dates_removed
            )
        # Get dates in new schedule that are not in old schedule
        dates_added = [d for d in dates_new if d not in dates_old]
        # Get the schedule recurrences
        recurrences = (
            self.collection.recurrence_db.get_recurrences_by_team_and_date_range(
                team_id=schedule_new.team_id,
                start_date=schedule_new.start_date,
                end_date=schedule_new.end_date,
            )
        )
        # Get the recurrences exclusions
        # fmt: off
        exclusions = self.collection.recurrence_exclusion_db\
            .get_recurrence_exclusions_by_rule_ids(
                rule_ids=[r.id for r in recurrences]
            )
        # fmt: on

        rec_id_to_exclusions: Dict[str, List[RecurrenceExclusion]] = {}
        for e in exclusions:
            if e.recurrence_rule_id not in rec_id_to_exclusions:
                rec_id_to_exclusions[e.recurrence_rule_id] = []
            rec_id_to_exclusions[e.recurrence_rule_id].append(e)
        # Get the recurrences assignments shifts
        shift_rec_ids: Set[str] = {
            r.occurrence_info.shift_id
            for r in recurrences
            if r.occurrence_info.shift_id is not None
        }
        shifts_rec = self.collection.shift_db.get_shifts_by_ids(
            shift_ids=list(shift_rec_ids)
        )
        shift_id_to_shift: Dict[str, Shift] = {shift.id: shift for shift in shifts_rec}
        # Create the recurrences assignments on the schedule period
        assignnments_created = []
        for recurrence in recurrences:
            assignments_recurrence = self._handle_recurrence_assignments_creation(
                recurrence=recurrence,
                period_dates=dates_added,
                schedule_id=schedule_new.id,
                create_first_assignment=True,
            )
            shift_rec = (
                shift_id_to_shift.get(recurrence.occurrence_info.shift_id, None)
                if recurrence.occurrence_info.shift_id
                else None
            )
            if shift_rec is None:
                raise ValueError(
                    f"Shift with ID {recurrence.occurrence_info.shift_id} does "
                    + "not exist."
                )
            assignments_recup = []
            if shift_rec.shift_type == ShiftType.DUTY:
                shifts_recup = self._get_recup_shifts(
                    shift_ids=[a.shift_id for a in assignments_recurrence]
                )
                assignments_recup = self._create_recuperation_assignments(
                    assignments_duty=assignments_recurrence,
                    shifts_recup=shifts_recup,
                )
            assignnments_created.extend(assignments_recurrence + assignments_recup)
        if assignnments_created:
            self.collection.assignment_db.create_assignments(assignnments_created)

    def get_assignments_and_recurrences(
        self,
        team_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> AssignmentsRecurrencesResult:
        if start_date is None or end_date is None:
            assignments = self.collection.assignment_db.get_assignments(team_id)
        else:
            assignments = self.collection.assignment_db.get_assignments_by_dates(
                team_id, start_date, end_date
            )
        recurrences = self.collection.recurrence_db.get_recurrences_by_team_id(
            team_id=team_id
        )
        return AssignmentsRecurrencesResult(
            assignments_created=[],
            assignments_read=assignments,
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=None,
            recurrences_read=recurrences,
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )

    def get_assignments_validated(
        self,
        team_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> List[Assignment]:
        schedules = self.collection.schedule_db.get_schedules(team_id=team_id)
        schedule_valid_ids = [
            s.id for s in schedules if s.status == ScheduleStatus.VALIDATED
        ]
        if not schedule_valid_ids:
            return []
        if start_date is None or end_date is None:
            return self.collection.assignment_db.get_assignments_by_schedule_ids(
                schedule_ids=schedule_valid_ids
            )
        # fmt: off
        return self.collection.assignment_db\
            .get_assignments_by_schedule_ids_and_date_range(
                schedule_ids=schedule_valid_ids,
                start_date=start_date,
                end_date=end_date,
            )
        # fmt: on

    def update_assignment_and_recurrence(
        self,
        assignment_new: Assignment,
        recurrence_update_scope: Optional[RecurrenceUpdateScope] = None,
        recurrence: Optional[RecurrenceRule] = None,
    ) -> AssignmentsRecurrencesResult:
        assignment_updated, assignment_old = self._update_main_assignment(
            assignment_new=assignment_new
        )
        (
            assignments_recup_created,
            assignments_recup_updated,
            assignments_recup_deleted_ids,
        ) = self._udpdate_recup_assignments(
            assignment_new=assignment_new, assignment_old=assignment_old
        )
        if recurrence_update_scope and recurrence:
            ar_result_rec_update = self._handle_recurrence_update(
                recurrence_update_scope=recurrence_update_scope,
                recurrence_new=recurrence,
                assignment=assignment_updated,
            )
            if ar_result_rec_update.recurrence_created:
                assignment_updated.source_id = (
                    ar_result_rec_update.recurrence_created.id
                )
                for ar_created in assignments_recup_created:
                    ar_created.source_id = ar_result_rec_update.recurrence_created.id
                for ar_updated in assignments_recup_updated:
                    ar_updated.source_id = ar_result_rec_update.recurrence_created.id
                self.collection.assignment_db.update_assignments(
                    assignments=[assignment_updated]
                    + assignments_recup_created
                    + assignments_recup_updated
                )

            ar_result_rec_update.assignments_created.extend(assignments_recup_created)
            ar_result_rec_update.assignments_updated.extend(
                [assignment_updated] + assignments_recup_updated
            )
            ar_result_rec_update.assignments_deleted_ids.extend(
                assignments_recup_deleted_ids
            )
            return ar_result_rec_update
        return AssignmentsRecurrencesResult(
            assignments_created=assignments_recup_created,
            assignments_read=[],
            assignments_updated=[assignment_updated] + assignments_recup_updated,
            assignments_deleted_ids=assignments_recup_deleted_ids,
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )

    def _update_main_assignment(
        self,
        assignment_new: Assignment,
    ) -> Tuple[Assignment, Assignment]:
        assignment_old = self.collection.assignment_db.get_assignment_by_id(
            assignment_new.id
        )
        if not assignment_old:
            raise ValueError(f"Assignment with ID {assignment_new.id} does not exist.")
        assignment_updated = self.collection.assignment_db.update_assignment(
            assignment=assignment_new
        )
        return assignment_updated, assignment_old

    def _udpdate_recup_assignments(
        self, assignment_new: Assignment, assignment_old: Assignment
    ) -> Tuple[List[Assignment], List[Assignment], List[str]]:
        assignments_recup_created: List[Assignment] = []
        assignments_recup_updated: List[Assignment] = []
        assignments_recup_deleted_ids: List[str] = []
        if assignment_old.shift_id == assignment_new.shift_id:
            if assignment_old.fixed != assignment_new.fixed:
                assignment_recup_old = (
                    self.collection.assignment_db.get_assignments_by_reference_id(
                        reference_id=assignment_old.id
                    )
                )
                for assignment in assignment_recup_old:
                    assignment.fixed = assignment_new.fixed
                    assignments_recup_updated.append(
                        self.collection.assignment_db.update_assignment(assignment)
                    )
            return (
                assignments_recup_created,
                assignments_recup_updated,
                assignments_recup_deleted_ids,
            )

        # Check if the shift type is changing
        shift_old = self.collection.shift_db.get_shift_by_id(assignment_old.shift_id)
        shift_new = self.collection.shift_db.get_shift_by_id(assignment_new.shift_id)

        if not shift_old or not shift_new:
            raise ValueError("Invalid shift ID provided.")

        if shift_old.shift_type == ShiftType.DUTY:
            assignments_recup_deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_reference_id(
                    reference_id=assignment_old.id
                )
            )

        if shift_new.shift_type == ShiftType.DUTY:
            shift_recup_new = self.collection.shift_db.get_recuperation_shift(
                shift_id=assignment_new.shift_id
            )
            if shift_recup_new:
                recuperation_assignment = Assignment(
                    id="",  # ID will be generated by the database
                    team_id=assignment_new.team_id,
                    schedule_id=assignment_new.schedule_id,
                    worker_id=assignment_new.worker_id,
                    date=assignment_new.date,
                    shift_id=shift_recup_new.id,
                    fixed=assignment_new.fixed,
                    source=assignment_new.source,
                    reference_assignment_id=assignment_new.id,
                )
                assignments_recup_created.append(
                    self.collection.assignment_db.create_assignment(
                        recuperation_assignment
                    )
                )
        return (
            assignments_recup_created,
            assignments_recup_updated,
            assignments_recup_deleted_ids,
        )

    def _handle_recurrence_update(
        self,
        recurrence_update_scope: RecurrenceUpdateScope,
        recurrence_new: RecurrenceRule,
        assignment: Assignment,
    ) -> AssignmentsRecurrencesResult:
        if recurrence_update_scope == RecurrenceUpdateScope.NONE:
            # Assignment did not have a recurrence, so we just update it
            # Do not create the assignment for the start date
            shift = self.collection.shift_db.get_shift_by_id(assignment.shift_id)
            if shift is None:
                raise ValueError(f"Shift with ID {assignment.shift_id} does not exist.")
            return self._handle_recurrence_and_assignments_creation(
                recurrence=recurrence_new,
                assignment=assignment,
                shift=shift,
                create_recurrence=True,
                create_first_assignment=False,
            )
        if recurrence_update_scope == RecurrenceUpdateScope.SINGLE:
            # Update single assignment (done outside of this method) and create
            # recurrence exception
            exclusion = RecurrenceExclusion(
                id="",  # ID will be generated by the database
                recurrence_rule_id=recurrence_new.id,
                excluded_date=assignment.date,
            )
            self.collection.recurrence_exclusion_db.create_recurrence_exclusion(
                exclusion
            )
            # TODO_: find solution in case we are changing the only assignment
            # for this recurrence
            return AssignmentsRecurrencesResult(
                assignments_created=[],
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=[],
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=None,
                recurrences_deleted_ids=[],
            )
        if recurrence_update_scope == RecurrenceUpdateScope.FUTURE:
            # Create new recurrence starting at the time of the assignment
            recurrence_created = RecurrenceRule(
                id="",  # ID will be generated by the database
                team_id=recurrence_new.team_id,
                occurrence_type=recurrence_new.occurrence_type,
                occurrence_info=OccurrenceInfo(
                    worker_id=assignment.worker_id,
                    shift_id=assignment.shift_id,
                ),
                repeat_every=recurrence_new.repeat_every,
                frequency_type=recurrence_new.frequency_type,
                week_days=recurrence_new.week_days,
                month_repeat_type=recurrence_new.month_repeat_type,
                recurrence_end_type=recurrence_new.recurrence_end_type,
                start_date=assignment.date,
                end_date=recurrence_new.end_date,
                number_of_occurrences=recurrence_new.number_of_occurrences,
            )
            recurrence_old = self.collection.recurrence_db.get_recurrence_by_id(
                recurrence_id=recurrence_new.id
            )
            if (
                recurrence_old.recurrence_end_type
                == RecurrenceEndType.NUMBER_OF_OCCURRENCES
                and recurrence_new.recurrence_end_type
                == RecurrenceEndType.NUMBER_OF_OCCURRENCES
                and recurrence_old.number_of_occurrences is not None
                and recurrence_new.number_of_occurrences
                == recurrence_old.number_of_occurrences
            ):
                period_dates = build_dates_list(
                    start_date=recurrence_old.start_date,
                    end_date=assignment.date,
                )
                dates_original_rec = generate_recurring_dates(
                    period_dates=period_dates,
                    recurrence_rule=recurrence_old,
                    exclusions=[],
                )
                past_occurrence_count = len(
                    [d for d in dates_original_rec if d < assignment.date]
                )
                recurrence_created.number_of_occurrences = max(
                    recurrence_old.number_of_occurrences - past_occurrence_count,
                    0,
                )

            # Update recurrence to end at date of assignment
            recurrence_old.recurrence_end_type = RecurrenceEndType.END_DATE
            recurrence_old.end_date = assignment.date + timedelta(days=-1)
            recurrence_updated = self.collection.recurrence_db.update_recurrence(
                recurrence_old
            )
            # Delete all future assignments for this recurrence
            # fmt: off
            deleted_assignments_ids = self.collection.assignment_db\
                .delete_assignments_by_source_id_from_date(
                    source_id=recurrence_new.id,
                    from_date=assignment.date + timedelta(days=1),
                )
            # fmt: on
            # Create new assignments for the new recurrence
            shift = self.collection.shift_db.get_shift_by_id(assignment.shift_id)
            if shift is None:
                raise ValueError(f"Shift with ID {assignment.shift_id} does not exist.")
            ar_result = self._handle_recurrence_and_assignments_creation(
                recurrence=recurrence_created,
                assignment=assignment,
                shift=shift,
                create_recurrence=True,
                create_first_assignment=False,
            )
            ar_result.assignments_deleted_ids.extend(deleted_assignments_ids)
            ar_result.recurrence_updated = recurrence_updated
            return ar_result
        if recurrence_update_scope == RecurrenceUpdateScope.ALL:
            recurrence_old = self.collection.recurrence_db.get_recurrence_by_id(
                recurrence_id=recurrence_new.id
            )
            # Update the recurrence
            recurrence_new.start_date = recurrence_old.start_date
            recurrence_new.occurrence_info.worker_id = assignment.worker_id
            recurrence_new.occurrence_info.shift_id = assignment.shift_id
            recurrence_updated = self.collection.recurrence_db.update_recurrence(
                recurrence_new
            )
            # Update all assignments for this recurrence (delete and create)
            assignments_deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_source_id(
                    source_id=recurrence_updated.id
                )
            )
            shift = self.collection.shift_db.get_shift_by_id(assignment.shift_id)
            if shift is None:
                raise ValueError(f"Shift with ID {assignment.shift_id} does not exist.")
            assignment.date = recurrence_updated.start_date
            ar_result = self._handle_recurrence_and_assignments_creation(
                recurrence=recurrence_updated,
                assignment=assignment,
                shift=shift,
                create_recurrence=False,
                create_first_assignment=True,
            )
            ar_result.assignments_deleted_ids.extend(assignments_deleted_ids)
            ar_result.recurrence_updated = recurrence_updated
            return ar_result
        raise ValueError(f"Invalid recurrence update scope: {recurrence_update_scope}")

    def delete_assignment_and_recurrence(
        self,
        assignment_id: str,
        recurrence_id: Optional[str] = None,
        recurrence_update_scope: Optional[RecurrenceUpdateScope] = None,
    ) -> AssignmentsRecurrencesResult:
        ar_result = AssignmentsRecurrencesResult(
            assignments_created=[],
            assignments_read=[],
            assignments_updated=[],
            assignments_deleted_ids=[],
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )
        if recurrence_id and recurrence_update_scope:
            ar_result = self._handle_recurrence_delete(
                assignment_id=assignment_id,
                recurrence_rule_id=recurrence_id,
                recurrence_update_scope=recurrence_update_scope,
            )
        deleted_ids = self.collection.assignment_db.delete_assignments_by_reference_id(
            reference_id=assignment_id
        )
        ar_result.assignments_deleted_ids.extend(deleted_ids)
        if assignment_id not in ar_result.assignments_deleted_ids:
            self.collection.assignment_db.delete_assignment(assignment_id)
            ar_result.assignments_deleted_ids.append(assignment_id)
        return ar_result

    def _handle_recurrence_delete(
        self,
        assignment_id: str,
        recurrence_rule_id: str,
        recurrence_update_scope: RecurrenceUpdateScope,
    ) -> AssignmentsRecurrencesResult:
        assignment = self.collection.assignment_db.get_assignment_by_id(assignment_id)
        if not assignment:
            raise ValueError(f"Assignment with ID {assignment_id} does not exist.")
        if recurrence_update_scope == RecurrenceUpdateScope.SINGLE:
            # Delete single assignment (done outside of this method) and create
            # recurrence exception
            exclusion = RecurrenceExclusion(
                id="",  # ID will be generated by the database
                recurrence_rule_id=recurrence_rule_id,
                excluded_date=assignment.date,
            )
            self.collection.recurrence_exclusion_db.create_recurrence_exclusion(
                exclusion
            )
            return AssignmentsRecurrencesResult(
                assignments_created=[],
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=[],
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=None,
                recurrences_deleted_ids=[],
            )
        if recurrence_update_scope == RecurrenceUpdateScope.FUTURE:
            # Update recurrence to end at date of assignment
            recurrence = self.collection.recurrence_db.get_recurrence_by_id(
                recurrence_rule_id
            )
            if not recurrence:
                raise ValueError(
                    f"Recurrence rule with ID {recurrence_rule_id} does not exist."
                )
            recurrence.recurrence_end_type = RecurrenceEndType.END_DATE
            recurrence.end_date = assignment.date + timedelta(days=-1)
            recurrence_updated = self.collection.recurrence_db.update_recurrence(
                recurrence
            )
            # Delete all future assignments for this recurrence
            # fmt: off
            deleted_assignments_ids = self.collection.assignment_db\
                .delete_assignments_by_source_id_from_date(
                    source_id=recurrence.id,
                    from_date=assignment.date,
                )
            # fmt: on
            return AssignmentsRecurrencesResult(
                assignments_created=[],
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=deleted_assignments_ids,
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=recurrence_updated,
                recurrences_deleted_ids=[],
            )
        if recurrence_update_scope == RecurrenceUpdateScope.ALL:
            # Delete all assignments for this recurrence
            assignments_deleted_ids = (
                self.collection.assignment_db.delete_assignments_by_source_id(
                    source_id=recurrence_rule_id
                )
            )
            # Delete the exclusions for this recurrence
            # fmt: off
            self.collection.recurrence_exclusion_db\
                .delete_recurrence_exclusions_by_rule_id(
                    rule_id=recurrence_rule_id
                )
            # fmt: on
            # Delete the recurrence
            self.collection.recurrence_db.delete_recurrence(recurrence_rule_id)
            return AssignmentsRecurrencesResult(
                assignments_created=[],
                assignments_read=[],
                assignments_updated=[],
                assignments_deleted_ids=assignments_deleted_ids,
                recurrence_created=None,
                recurrences_read=[],
                recurrence_updated=None,
                recurrences_deleted_ids=[recurrence_rule_id],
            )
        raise ValueError(f"Invalid recurrence update scope: {recurrence_update_scope}")

    def duplicate_period(
        self, campaign: Schedule, duplicate: DuplicateRequest
    ) -> AssignmentsRecurrencesResult:
        date_mapping = build_duplicate_date_mapping(duplicate=duplicate)
        source_period = list(date_mapping.keys())
        target_period = list(date_mapping.values())

        assignments_source, assignments_target = self._get_assignments_for_periods(
            source_period=source_period,
            target_period=target_period,
            team_id=campaign.team_id,
        )
        (
            a_source_duplicate_ids,
            a_target_keep_ids,
            a_target_delete_ids,
            exclusions_target_create,
        ) = self._build_assignment_and_exclusion_lists(
            source_period=source_period,
            target_period=target_period,
            date_mapping=date_mapping,
            assignments_source=assignments_source,
            assignments_target=assignments_target,
        )

        validate_duplicate_lists(
            source_ids=[a.id for a in assignments_source],
            target_ids=[a.id for a in assignments_target],
            source_duplicate_ids=a_source_duplicate_ids,
            target_keep_ids=a_target_keep_ids,
            target_delete_ids=a_target_delete_ids,
        )

        a_to_create = self._build_duplicate_assignments(
            assignments_source=assignments_source,
            date_mapping=date_mapping,
            a_source_duplicate_ids=a_source_duplicate_ids,
            campaign_id=campaign.id,
        )

        ar_result = self._apply_changes_to_database(
            a_to_create=a_to_create,
            a_target_delete_ids=a_target_delete_ids,
            exclusions_target_create=exclusions_target_create,
        )

        shifts_recup = self._get_recup_shifts(
            shift_ids=[a.shift_id for a in ar_result.assignments_created]
        )
        assignments_recup = self._create_recuperation_assignments(
            assignments_duty=ar_result.assignments_created,
            shifts_recup=shifts_recup,
        )
        if assignments_recup:
            assignments_recup_saved = self.collection.assignment_db.create_assignments(
                assignments_recup
            )
            ar_result.assignments_created.extend(assignments_recup_saved)
        return ar_result

    def _get_assignments_for_periods(
        self,
        source_period: List[date],
        target_period: List[date],
        team_id: str,
    ) -> Tuple[List[Assignment], List[Assignment]]:
        assignments_source = self.collection.assignment_db.get_assignments_by_dates(
            team_id=team_id,
            start_date=min(source_period),
            end_date=max(source_period),
        )
        assignments_target = self.collection.assignment_db.get_assignments_by_dates(
            team_id=team_id,
            start_date=min(target_period),
            end_date=max(target_period),
        )
        return assignments_source, assignments_target

    @staticmethod
    def _build_assignment_and_exclusion_lists(
        source_period: List[date],
        target_period: List[date],
        date_mapping: Dict[date, date],
        assignments_source: List[Assignment],
        assignments_target: List[Assignment],
    ) -> Tuple[
        List[str],
        List[str],
        List[str],
        List[RecurrenceExclusion],
    ]:
        a_source_duplicate_ids = []
        a_target_keep_ids = []
        a_target_delete_ids = []
        exclusions_target_create = []

        for a_source in assignments_source:
            if a_source.date not in source_period:
                continue
            if a_source.reference_assignment_id:
                continue

            if a_source.source_id:
                matching_target_assignment = next(
                    (
                        a
                        for a in assignments_target
                        if a.date == date_mapping[a_source.date]
                        and a.worker_id == a_source.worker_id
                        and a.shift_id == a_source.shift_id
                        and a.source_id == a_source.source_id
                    ),
                    None,
                )
                if matching_target_assignment:
                    a_target_keep_ids.append(matching_target_assignment.id)
                    continue
            a_source_duplicate_ids.append(a_source.id)

        for a_target in assignments_target:
            if a_target.date not in target_period:
                continue
            if a_target.id in a_target_keep_ids:
                continue

            if a_target.source_id:
                exclusions_target_create.append(
                    RecurrenceExclusion(
                        id="",
                        recurrence_rule_id=a_target.source_id,
                        excluded_date=a_target.date,
                    )
                )
            a_target_delete_ids.append(a_target.id)

        return (
            a_source_duplicate_ids,
            a_target_keep_ids,
            a_target_delete_ids,
            exclusions_target_create,
        )

    @staticmethod
    def _build_duplicate_assignments(
        assignments_source: List[Assignment],
        date_mapping: Dict[date, date],
        a_source_duplicate_ids: List[str],
        campaign_id: str,
    ) -> List[Assignment]:
        a_to_create = []

        for a_source in assignments_source:
            if a_source.id not in a_source_duplicate_ids:
                continue
            if a_source.reference_assignment_id:
                continue
            a_to_create.append(
                Assignment(
                    id="",
                    team_id=a_source.team_id,
                    schedule_id=campaign_id,
                    worker_id=a_source.worker_id,
                    date=date_mapping[a_source.date],
                    shift_id=a_source.shift_id,
                    fixed=a_source.fixed,
                    source=AssignmentSource.DUPLICATE,
                    reference_assignment_id=None,
                    source_id=None,
                )
            )

        return a_to_create

    def _apply_changes_to_database(
        self,
        a_to_create: List[Assignment],
        a_target_delete_ids: List[str],
        exclusions_target_create: List[RecurrenceExclusion],
    ) -> AssignmentsRecurrencesResult:
        # Create the new assignments
        a_created = self.collection.assignment_db.create_assignments(a_to_create)
        # Delete the old assignments
        a_deleted_ids = self.collection.assignment_db.delete_assignments(
            assignment_ids=a_target_delete_ids
        )
        # Create the exclusions
        self.collection.recurrence_exclusion_db.create_recurrence_exclusions(
            exclusions=exclusions_target_create
        )
        return AssignmentsRecurrencesResult(
            assignments_created=a_created,
            assignments_read=[],
            assignments_updated=[],
            assignments_deleted_ids=a_deleted_ids,
            recurrence_created=None,
            recurrences_read=[],
            recurrence_updated=None,
            recurrences_deleted_ids=[],
        )
