/**
 * Example migration from legacy team invitation functions to new hooks/API
 *
 * This file demonstrates how to migrate existing code from the old pattern
 * to the new authenticated API pattern.
 */

import React, { useState, useEffect } from "react";
// NEW: Import the hooks
import {
  useCreateTeamInvitation,
  useGetTeamInvitations,
  useAcceptTeamInvitation,
  useRejectTeamInvitation,
} from "@/hooks/useTeamInvitation";
// Types
import {
  TeamInvitationT,
  TeamInvitationType,
  TeamInvitationStatus,
} from "@/types/team-invitation";

// OLD WAY (deprecated - still works but not recommended)
// import {
//   createTeamInvitation,
//   getTeamInvitations,
//   acceptTeamInvitation,
//   rejectTeamInvitation,
// } from '@/app/lib/team-invitation';

interface MigrationExampleProps {
  teamId: string;
}

export default function MigrationExample({ teamId }: MigrationExampleProps) {
  const [invitations, setInvitations] = useState<TeamInvitationT[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // NEW: Use hooks for team invitation operations
  const createInvitation = useCreateTeamInvitation();
  const getInvitations = useGetTeamInvitations();
  const acceptInvitation = useAcceptTeamInvitation();
  const rejectInvitation = useRejectTeamInvitation();

  // Example: Loading invitations
  useEffect(() => {
    const loadInvitations = async () => {
      if (!teamId) return;

      setLoading(true);
      setError(null);

      try {
        // NEW WAY: Using authenticated hook
        const data = await getInvitations(teamId);
        setInvitations(data);

        // OLD WAY (deprecated):
        // const data = await getTeamInvitations(teamId);
        // setInvitations(data);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to load invitations"
        );
      } finally {
        setLoading(false);
      }
    };

    loadInvitations();
  }, [teamId, getInvitations]); // Note: getInvitations is stable due to useCallback

  // Example: Creating a new invitation
  const handleCreateInvitation = async (email: string) => {
    if (!email || !teamId) return;

    setLoading(true);
    setError(null);

    try {
      // NEW WAY: Using authenticated hook
      const newInvitation: Partial<TeamInvitationT> = {
        email,
        teamId,
        type: TeamInvitationType.MEMBER,
        firstName: null,
        lastName: null,
        workerId: null,
        token: "", // Will be generated by backend
        status: TeamInvitationStatus.PENDING,
        createdBy: null,
        createdAt: null as any, // Will be set by backend
        expiresAt: null as any, // Will be set by backend
        lastSentAt: null,
      };

      const invitation = await createInvitation(
        newInvitation as TeamInvitationT,
        teamId
      );

      // Update local state
      setInvitations((prev) => [...prev, invitation]);

      // OLD WAY (deprecated):
      // const invitation = await createTeamInvitation(newInvitation as TeamInvitationT, teamId);
      // setInvitations(prev => [...prev, invitation]);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to create invitation"
      );
    } finally {
      setLoading(false);
    }
  };

  // Example: Accepting an invitation
  const handleAcceptInvitation = async (token: string) => {
    if (!token) return;

    setLoading(true);
    setError(null);

    try {
      // NEW WAY: Using authenticated hook
      const teamWithMembership = await acceptInvitation(token);
      console.log("Joined team:", teamWithMembership);

      // Refresh invitations list
      const updatedInvitations = await getInvitations(teamId);
      setInvitations(updatedInvitations);

      // OLD WAY (deprecated):
      // const teamWithMembership = await acceptTeamInvitation(token);
      // console.log('Joined team:', teamWithMembership);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to accept invitation"
      );
    } finally {
      setLoading(false);
    }
  };

  // Example: Rejecting an invitation
  const handleRejectInvitation = async (token: string) => {
    if (!token) return;

    setLoading(true);
    setError(null);

    try {
      // NEW WAY: Using authenticated hook
      await rejectInvitation(token);

      // Refresh invitations list
      const updatedInvitations = await getInvitations(teamId);
      setInvitations(updatedInvitations);

      // OLD WAY (deprecated):
      // const success = await rejectTeamInvitation(token);
      // if (success) {
      //   // Refresh invitations list
      //   const updatedInvitations = await getTeamInvitations(teamId);
      //   setInvitations(updatedInvitations);
      // }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to reject invitation"
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <h2>Team Invitations Migration Example</h2>

      {error && (
        <div style={{ color: "red", marginBottom: "1rem" }}>Error: {error}</div>
      )}

      {loading && <div>Loading...</div>}

      <div>
        <h3>Invitations ({invitations.length})</h3>
        {invitations.map((invitation) => (
          <div
            key={invitation.id}
            style={{
              border: "1px solid #ccc",
              padding: "1rem",
              margin: "0.5rem 0",
            }}
          >
            <p>
              <strong>Email:</strong> {invitation.email}
            </p>
            <p>
              <strong>Status:</strong> {invitation.status}
            </p>
            <p>
              <strong>Type:</strong> {invitation.type}
            </p>
            {invitation.status === "pending" && (
              <div>
                <button
                  onClick={() => handleAcceptInvitation(invitation.token)}
                >
                  Accept
                </button>
                <button
                  onClick={() => handleRejectInvitation(invitation.token)}
                >
                  Reject
                </button>
              </div>
            )}
          </div>
        ))}
      </div>

      <div style={{ marginTop: "2rem" }}>
        <h3>Create New Invitation</h3>
        <button
          onClick={() => handleCreateInvitation("test@example.com")}
          disabled={loading}
        >
          Create Test Invitation
        </button>
      </div>
    </div>
  );
}

/* 
MIGRATION BENEFITS:

1. 🔒 AUTHENTICATION: New hooks automatically handle authentication state
2. 🎯 TYPE SAFETY: Better TypeScript support and error handling
3. 🔄 CONSISTENT PATTERNS: Same structure as other API hooks in the project
4. 📝 BETTER ERRORS: More descriptive error messages
5. 🛡️ SECURITY: Input validation and sanitization
6. 🎛️ LOADING STATES: Hooks can be extended to return loading states
7. 📊 LOGGING: Built-in development logging for debugging

BACKWARD COMPATIBILITY:

The old functions still work but show deprecation warnings:
- createTeamInvitation -> useCreateTeamInvitation hook or TeamInvitationApi.createTeamInvitation
- getTeamInvitations -> useGetTeamInvitations hook or TeamInvitationApi.getTeamInvitations
- acceptTeamInvitation -> useAcceptTeamInvitation hook or TeamInvitationApi.acceptTeamInvitation
- rejectTeamInvitation -> useRejectTeamInvitation hook or TeamInvitationApi.rejectTeamInvitation

MIGRATION STEPS:

1. Replace imports from '@/app/lib/team-invitation' with hooks from '@/hooks/useTeamInvitation'
2. Call hooks at the component level (following React rules of hooks)
3. Use the returned functions instead of calling the legacy functions directly
4. Update error handling to work with the new error format
5. Test thoroughly with authentication states

*/
