[tool.poetry]
name = "shared"
version = "0.1.0"
description = ""
authors = ["Felipe Kharaba"]
readme = "README.md"
packages = [
    { include = "shared", from = "src" },
]
include = ["py.typed"]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
mongoengine = "^0.29.1"
loguru = "^0.7.2"
mongo-types = "^0.15.1"
isort = "^5.13.2"
black = "^24.10.0"
mypy = "^1.13.0"
flake8 = "^7.1.1"
autoflake = "^2.3.1"
fastapi = "^0.115.6"
pylint = "^3.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
