[project]
name = "shared"
version = "0.1.403"
description = ""
readme = "README.md"
authors = [ { name = "Felipe Kharaba" } ]
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.2",
    "mongo-types>=0.15.1",
    "mypy>=1.13.0",
    "fastapi>=0.115.6",
    "pylint>=3.3.2",
    "pytest>=8.3.5",
    "dotenv>=0.9.9",
    "pymongo[aws]>=4.11.3",
    "pyhumps>=3.8.0",
    "pydantic>=2.11.7",
    "boto3>=1.35.0",
    "botocore>=1.35.0",
    "pytest-asyncio>=1.1.0",
    "email-validator>=2.3.0",
]

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["shared*"]

[tool.setuptools.package-data]
"shared" = ["py.typed"]

[dependency-groups]
dev = [
    "ruff>=0.15.8",
]

[tool.ruff]
line-length = 88
target-version = "py314"
lint.extend-select = ["I"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["shared"]
combine_as_imports = true
multi_line_output = 3
