[tool.poetry]
name = "shared"
version = "0.1.202"
description = ""
authors = ["Felipe Kharaba"]
readme = "README.md"
packages = [
    { include = "shared", from = "src" },
]
include = ["py.typed"]

[tool.poetry.dependencies]
python = ">=3.12,<=3.14"
loguru = "^0.7.2"
mongo-types = "^0.15.1"
mypy = "^1.13.0"
flake8 = "^7.1.1"
autoflake = "^2.3.1"
fastapi = "^0.115.6"
pylint = "^3.3.2"
black = "^25.1.0"
pytest = "^8.3.5"
dotenv = "^0.9.9"
isort = "^6.0.1"
pymongo = {extras = ["aws"], version = "^4.11.3"}
pyhumps = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
