/**
 * API test for constraint creation functionality
 *
 * This test verifies that constraint creation via API works correctly
 * for setting up test data in E2E tests.
 */

import { test, expect } from "@playwright/test";
import { ConstraintTestBase } from "../../utils/constraint-test-base";

const constraintTestBase = new ConstraintTestBase();

test.describe("Constraint API Tests", () => {
  test.beforeEach(async () => {
    // Setup the constraint test environment
    await constraintTestBase.setupConstraintTests(test.info().workerIndex);
  });

  test("should create constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint creation"
      );
      return;
    }

    const template = templates[0];
    console.log(
      `Using template: ${template.id} (type: ${template.constraintType})`
    );

    // Create a test constraint using template-based block generation
    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerIndex: 0,
        shiftIndex: 0,
        numberValue: 2,
        stringOverrides: {
          5: "should work", // TEXT block
          0: "at least", // OPERATOR block
          2: "per week", // TIMING block
        },
        hard: true,
        priority: "high",
        active: true,
      });

    expect(createdConstraint.constraintId).toBeTruthy();
    expect(createdConstraint.teamId).toBeTruthy();

    console.log(`✅ Created constraint: ${createdConstraint.constraintId}`);

    // Verify constraint can be retrieved
    const constraints = await constraintTestBase.getTestConstraints();
    const foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.constraintId
    );

    expect(foundConstraint).toBeTruthy();
    expect(foundConstraint.hard).toBe(true);

    // Since text is generated by backend, just verify it's not empty
    expect(foundConstraint.text).toBeTruthy();
    expect(typeof foundConstraint.text).toBe("string");

    console.log(
      `✅ Constraint verified in database with generated text: ${foundConstraint.text}`
    );

    // Clean up
    await constraintTestBase.deleteTestConstraint(
      createdConstraint.constraintId
    );
    console.log(`✅ Constraint cleanup completed`);
  });

  test("should update constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint update"
      );
      return;
    }

    const template = templates[0];

    // Create a test constraint first using template-based generation
    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerIndex: 0,
        shiftIndex: 0,
        numberValue: 2,
        stringOverrides: {
          5: "should work", // TEXT block
          0: "at least", // OPERATOR block
          2: "per week", // TIMING block
        },
        hard: true,
        priority: "high",
        active: true,
      });

    // Update the constraint
    const updates = {
      text: "Updated constraint text",
      hard: false,
      priority: "low",
    };

    const updatedConstraint = await constraintTestBase.updateTestConstraint(
      createdConstraint.constraintId,
      updates
    );

    expect(updatedConstraint.constraintId).toBe(createdConstraint.constraintId);

    // Verify the updates were applied
    const constraints = await constraintTestBase.getTestConstraints();
    const foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.constraintId
    );

    expect(foundConstraint.text).toBe("Updated constraint text");
    expect(foundConstraint.hard).toBe(false);

    console.log(
      `✅ Constraint updated successfully: ${foundConstraint.text}, hard: ${foundConstraint.hard}`
    );

    // Clean up
    await constraintTestBase.deleteTestConstraint(
      createdConstraint.constraintId
    );
  });

  test("should delete constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint deletion"
      );
      return;
    }

    const template = templates[0];

    // Create a test constraint first using template-based generation
    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerIndex: 0,
        shiftIndex: 0,
        numberValue: 1,
        stringOverrides: {
          5: "should work", // TEXT block
          0: "exactly", // OPERATOR block
          2: "per day", // TIMING block
        },
        hard: true,
        priority: "medium",
        active: true,
      });

    // Verify it exists
    let constraints = await constraintTestBase.getTestConstraints();
    let foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.constraintId
    );
    expect(foundConstraint).toBeTruthy();

    // Delete the constraint
    await constraintTestBase.deleteTestConstraint(
      createdConstraint.constraintId
    );

    // Verify it's deleted
    constraints = await constraintTestBase.getTestConstraints();
    foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.constraintId
    );
    expect(foundConstraint).toBeFalsy();

    console.log(`✅ Constraint deleted successfully`);
  });

  test("should retrieve constraint templates successfully", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();

    expect(Array.isArray(templates)).toBe(true);
    console.log(`✅ Retrieved ${templates.length} constraint templates`);

    if (templates.length > 0) {
      const template = templates[0];
      expect(template.id).toBeTruthy();
      expect(template.constraintType).toBeDefined();
      expect(template.text).toBeTruthy();

      console.log(
        `✅ Template validation passed: ${template.id} - ${template.text}`
      );
    }
  });
});
