/**
 * API test for constraint creation functionality
 *
 * This test verifies that constraint creation via API works correctly
 * for setting up test data in E2E tests.
 */

import { test, expect } from "@playwright/test";
import { ConstraintTestBase } from "../../utils/constraint-test-base";

const constraintTestBase = new ConstraintTestBase();

test.describe("Constraint API Tests", () => {
  test.beforeEach(async () => {
    // Setup the constraint test environment
    await constraintTestBase.setupConstraintTests(test.info().workerIndex);
  });

  test("should create constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint creation",
      );
      return;
    }

    const template = templates[0];
    console.log(
      `Using template: ${template.id} (type: ${template.constraintType})`,
    );

    // Create a test constraint using template-based block generation
    const testWorkers = constraintTestBase.getTestWorkers();
    const testShifts = constraintTestBase.getTestShifts();

    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id, // Use first worker ID
        shiftId: testShifts[0].id, // Use first shift ID
        numberValue: 2,
        hard: true,
        priority: "high",
        active: true,
      });

    expect(createdConstraint.id).toBeTruthy();
    expect(createdConstraint.teamId).toBeTruthy();

    console.log(`✅ Created constraint: ${createdConstraint.id}`);

    // Verify constraint can be retrieved
    const constraints = await constraintTestBase.getTestConstraints();
    const foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.id,
    );

    expect(foundConstraint).toBeTruthy();
    expect(foundConstraint.hard).toBe(true);

    // Since text is generated by backend, just verify it's not empty
    expect(foundConstraint.text).toBeTruthy();
    expect(typeof foundConstraint.text).toBe("string");

    console.log(
      `✅ Constraint verified in database with generated text: ${foundConstraint.text}`,
    );

    // Clean up
    await constraintTestBase.deleteTestConstraint(createdConstraint.id);
    console.log(`✅ Constraint cleanup completed`);
  });

  test("should update constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint update",
      );
      return;
    }

    const template = templates[0];

    // Create a test constraint first using template-based generation
    const testWorkers = constraintTestBase.getTestWorkers();
    const testShifts = constraintTestBase.getTestShifts();

    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id, // Use first worker ID
        shiftId: testShifts[0].id, // Use first shift ID
        numberValue: 2,
        hard: true,
        priority: "high",
        active: true,
      });

    // Update the constraint
    const updates = {
      text: "Updated constraint text",
      hard: false,
      priority: "low",
    };

    const updatedConstraint = await constraintTestBase.updateTestConstraint(
      createdConstraint.id,
      updates,
    );

    expect(updatedConstraint.id).toBe(createdConstraint.id);

    // Verify the updates were applied
    const constraints = await constraintTestBase.getTestConstraints();
    const foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.id,
    );

    expect(foundConstraint.hard).toBe(false);

    console.log(
      `✅ Constraint updated successfully: hard: ${foundConstraint.hard}`,
    );

    // Clean up
    await constraintTestBase.deleteTestConstraint(createdConstraint.id);
  });

  test("should delete constraint via API successfully", async () => {
    // Get available constraint templates
    const templates = await constraintTestBase.getTestConstraintTemplates();

    if (templates.length === 0) {
      test.skip(
        true,
        "No constraint templates available - cannot test constraint deletion",
      );
      return;
    }

    const template = templates[0];

    // Create a test constraint first using template-based generation
    const testWorkers = constraintTestBase.getTestWorkers();
    const testShifts = constraintTestBase.getTestShifts();

    const createdConstraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id, // Use first worker ID
        shiftId: testShifts[0].id, // Use first shift ID
        numberValue: 1,
        hard: true,
        priority: "medium",
        active: true,
      });

    // Verify it exists
    let constraints = await constraintTestBase.getTestConstraints();
    let foundConstraint = constraints.find(
      (c) => c.id === createdConstraint.id,
    );
    expect(foundConstraint).toBeTruthy();

    // Delete the constraint
    await constraintTestBase.deleteTestConstraint(createdConstraint.id);

    // Verify it's deleted
    constraints = await constraintTestBase.getTestConstraints();
    foundConstraint = constraints.find((c) => c.id === createdConstraint.id);
    expect(foundConstraint).toBeFalsy();

    console.log(`✅ Constraint deleted successfully`);
  });

  test("should retrieve constraint templates successfully", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();

    expect(Array.isArray(templates)).toBe(true);
    console.log(`✅ Retrieved ${templates.length} constraint templates`);

    if (templates.length > 0) {
      const template = templates[0];
      expect(template.id).toBeTruthy();
      expect(template.constraintType).toBeDefined();
      expect(template.text).toBeTruthy();

      console.log(
        `✅ Template validation passed: ${template.id} - ${template.text}`,
      );
    }
  });

  test("should create constraints with specific worker ID", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testWorkers = constraintTestBase.getTestWorkers();
    const testShifts = constraintTestBase.getTestShifts();

    // Test with first worker
    const constraint1 =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id,
        shiftId: testShifts[0].id,
        numberValue: 1,
      });
    expect(constraint1.id).toBeTruthy();

    // Test with second worker
    const constraint2 =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[1].id,
        shiftId: testShifts[0].id,
        numberValue: 2,
      });
    expect(constraint2.id).toBeTruthy();

    console.log(
      `✅ Created constraints for specific workers: ${constraint1.id}, ${constraint2.id}`,
    );
  });

  test("should create constraints with all workers option", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testShifts = constraintTestBase.getTestShifts();

    const constraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: "all",
        shiftId: testShifts[0].id,
        numberValue: 3,
      });

    expect(constraint.id).toBeTruthy();
    console.log(`✅ Created constraint for all workers: ${constraint.id}`);
  });

  test("should create constraints with all shifts option", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testWorkers = constraintTestBase.getTestWorkers();

    const constraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id,
        shiftId: "all",
        numberValue: 2,
      });

    expect(constraint.id).toBeTruthy();
    console.log(`✅ Created constraint for all shifts: ${constraint.id}`);
  });

  test("should create constraints with duty option", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testWorkers = constraintTestBase.getTestWorkers();

    const constraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id,
        shiftId: "duty",
        numberValue: 1,
      });

    expect(constraint.id).toBeTruthy();
    console.log(`✅ Created constraint with duty option: ${constraint.id}`);
  });

  test("should create constraints with no-duty option", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testWorkers = constraintTestBase.getTestWorkers();

    const constraint =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: testWorkers[0].id,
        shiftId: "no-duty",
        numberValue: 0,
      });

    expect(constraint.id).toBeTruthy();
    console.log(`✅ Created constraint with no-duty option: ${constraint.id}`);
  });

  test("should create constraints with default parameters", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];

    // Test with no parameters (should use defaults)
    const constraint =
      await constraintTestBase.createTestConstraintFromTemplate(template);

    expect(constraint.id).toBeTruthy();
    console.log(
      `✅ Created constraint with default parameters: ${constraint.id}`,
    );
  });

  test("should create constraints with all combinations", async () => {
    const templates = await constraintTestBase.getTestConstraintTemplates();
    if (templates.length === 0) {
      test.skip(true, "No constraint templates available");
      return;
    }

    const template = templates[0];
    const testWorkers = constraintTestBase.getTestWorkers();

    // Test all workers + all shifts
    const constraint1 =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: "all",
        shiftId: "all",
        numberValue: 5,
      });

    // Test all workers + duty
    const constraint2 =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: "all",
        shiftId: "duty",
        numberValue: 3,
      });

    // Test all workers + no-duty
    const constraint3 =
      await constraintTestBase.createTestConstraintFromTemplate(template, {
        workerId: "all",
        shiftId: "no-duty",
        numberValue: 1,
      });

    expect(constraint1.id).toBeTruthy();
    expect(constraint2.id).toBeTruthy();
    expect(constraint3.id).toBeTruthy();

    console.log(
      `✅ Created constraints with all combinations: ${constraint1.id}, ${constraint2.id}, ${constraint3.id}`,
    );
  });
});
