from shared.schemas.schemas.attribute import Attribute, AttributeOwnerType
from shared.schemas.schemas.config import Config
from shared.schemas.schemas.constraint import (
    Block,
    BlockNameOptions,
    BlockTypeOptions,
    ConstraintBuild,
    ConstraintBuildAugmented,
    ConstraintFai,
    ConstraintFil,
    ConstraintOperator,
    ConstraintOrd,
    Constraints,
    ConstraintSeq,
    ConstraintSum,
    ConstraintType,
    MissingAttribute,
    ShiftWorkerOption,
    SWOIdTypes,
    Template,
    TemplateBlock,
    VarDaySelectorOptions,
    VarShiftSelectorOptions,
    VarWorkerSelectorOptions,
)
from shared.schemas.schemas.coverage import (
    Coverage,
    CoverageSelector,
    DailyShiftDemand,
    DSDSourceType,
    ShiftDemand,
)
from shared.schemas.schemas.dimension import (
    Dimension,
    DimensionEntryType,
    DimensionType,
    DimEntry,
)
from shared.schemas.schemas.export_options import ExportOptions, ExportPeriodOptions
from shared.schemas.schemas.request import Request, RequestAugmented, RequestStatus
from shared.schemas.schemas.schedule import (
    Assignment,
    Breach,
    ObjectiveCategory,
    QuickStaffing,
    Schedule,
    ScheduleSolveStatus,
    ScheduleStatus,
    Variable,
)
from shared.schemas.schemas.shift import (
    Shift,
    ShiftLeaveType,
    ShiftRestType,
    ShiftType,
    Staffing,
)
from shared.schemas.schemas.stats import Stats, StatsHeader, StatsOptions, StatsValue
from shared.schemas.schemas.team import Specialty, Team
from shared.schemas.schemas.user import PasswordData, User, UserAuth, UserDashboard
from shared.schemas.schemas.worker import Worker

# pylint: disable=R0801
__all__ = [
    "Attribute",
    "AttributeOwnerType",
    "Config",
    "Assignment",
    "Block",
    "BlockNameOptions",
    "BlockTypeOptions",
    "ConstraintBuild",
    "ConstraintBuildAugmented",
    "ConstraintFai",
    "ConstraintFil",
    "ConstraintOperator",
    "ConstraintOrd",
    "Constraints",
    "ConstraintSeq",
    "ConstraintSum",
    "ConstraintType",
    "MissingAttribute",
    "ShiftWorkerOption",
    "SWOIdTypes",
    "Template",
    "TemplateBlock",
    "VarDaySelectorOptions",
    "VarShiftSelectorOptions",
    "VarWorkerSelectorOptions",
    "Coverage",
    "CoverageSelector",
    "DailyShiftDemand",
    "DSDSourceType",
    "ShiftDemand",
    "Dimension",
    "DimensionEntryType",
    "DimensionType",
    "DimEntry",
    "ExportOptions",
    "ExportPeriodOptions",
    "Request",
    "RequestAugmented",
    "RequestStatus",
    "Breach",
    "ObjectiveCategory",
    "QuickStaffing",
    "Schedule",
    "ScheduleSolveStatus",
    "ScheduleStatus",
    "Variable",
    "Shift",
    "ShiftLeaveType",
    "ShiftRestType",
    "ShiftType",
    "Staffing",
    "StatsOptions",
    "Stats",
    "StatsHeader",
    "StatsValue",
    "Specialty",
    "Team",
    "PasswordData",
    "User",
    "UserAuth",
    "UserDashboard",
    "Worker",
]
