from shared.schemas.schemas.assignment import Assignment
from shared.schemas.schemas.attribute import Attribute, AttributeOwnerType
from shared.schemas.schemas.breach import Breach, ObjectiveCategory, Variable
from shared.schemas.schemas.config import Config
from shared.schemas.schemas.constraint import (
    Block,
    BlockNameOptions,
    BlockTypeOptions,
    ConfigurationConstraintPenalty,
    Constraint,
    ConstraintBuild,
    ConstraintBuildAugmented,
    ConstraintFai,
    ConstraintFil,
    ConstraintOperator,
    ConstraintOrd,
    Constraints,
    ConstraintSeq,
    ConstraintSum,
    ConstraintType,
    CoveragePenalty,
    MissingAttribute,
    Penalties,
    Penalty,
    ShiftWorkerOption,
    SWOIdTypes,
    SystemConstraintPenalty,
    Template,
    TemplateBlock,
    UserConstraintPenalty,
    VarDaySelectorOptions,
    VarShiftSelectorOptions,
    VarWorkerSelectorOptions,
)
from shared.schemas.schemas.coverage import Coverage
from shared.schemas.schemas.coverage_selector import CoverageSelector
from shared.schemas.schemas.daily_shift_demand import (
    DailyShiftDemand,
    DSDSourceType,
)
from shared.schemas.schemas.dim_entry import DimEntry
from shared.schemas.schemas.dimension import (
    Dimension,
    DimensionEntryType,
    DimensionType,
)
from shared.schemas.schemas.engine import (
    ConfigurationConstraints,
    CustomSolverParams,
    EngineInputs,
    EngineInputsAugmented,
    EngineOutputs,
    EngineOutputsAugmented,
    ModelConfig,
    ModelSetup,
    SolverParams,
    SolveStrategy,
    SystemConstraints,
)
from shared.schemas.schemas.export_options import (
    ExportOptions,
    ExportPeriodOptions,
)
from shared.schemas.schemas.link_shift import LinkShift
from shared.schemas.schemas.model_output import ModelOutput, ModelOutputStatus
from shared.schemas.schemas.request import (
    Request,
    RequestAugmented,
    RequestStatus,
)
from shared.schemas.schemas.schedule import (
    QuickStaffing,
    Schedule,
    ScheduleSolveStatus,
    ScheduleStatus,
    SolveDetails,
    SolveDetailsStatus,
    WorkTimeTable,
    WorkTimeTableData,
)
from shared.schemas.schemas.shift import (
    Shift,
    ShiftLeaveType,
    ShiftRestType,
    ShiftType,
    Staffing,
)
from shared.schemas.schemas.shift_demand import ShiftDemand
from shared.schemas.schemas.specialty import Specialty
from shared.schemas.schemas.stats import (
    HeaderUnitOptions,
    Stats,
    StatsHeader,
    StatsOptions,
    StatsTimeFrameOptions,
    StatsUnitOptions,
    StatsValue,
)
from shared.schemas.schemas.task import TaskServices
from shared.schemas.schemas.team import Team
from shared.schemas.schemas.user import (
    Language,
    PasswordData,
    User,
    UserAuth,
    UserDashboard,
)
from shared.schemas.schemas.worker import Worker, WorkerDates

# pylint: disable=R0801
__all__ = [
    "Attribute",
    "AttributeOwnerType",
    "Config",
    "Assignment",
    "Block",
    "BlockNameOptions",
    "BlockTypeOptions",
    "ConfigurationConstraintPenalty",
    "Constraint",
    "ConstraintBuild",
    "ConstraintBuildAugmented",
    "ConstraintFai",
    "ConstraintFil",
    "ConstraintOperator",
    "ConstraintOrd",
    "Constraints",
    "ConstraintSeq",
    "ConstraintSum",
    "ConstraintType",
    "CoveragePenalty",
    "MissingAttribute",
    "Penalties",
    "Penalty",
    "ShiftWorkerOption",
    "SWOIdTypes",
    "SystemConstraintPenalty",
    "Template",
    "TemplateBlock",
    "UserConstraintPenalty",
    "VarDaySelectorOptions",
    "VarShiftSelectorOptions",
    "VarWorkerSelectorOptions",
    "Coverage",
    "CoverageSelector",
    "DailyShiftDemand",
    "DSDSourceType",
    "ShiftDemand",
    "Dimension",
    "DimensionEntryType",
    "DimensionType",
    "DimEntry",
    "ConfigurationConstraints",
    "CustomSolverParams",
    "EngineInputs",
    "EngineInputsAugmented",
    "EngineOutputs",
    "EngineOutputsAugmented",
    "ModelConfig",
    "ModelSetup",
    "SolverParams",
    "SolveStrategy",
    "SystemConstraints",
    "ExportOptions",
    "ExportPeriodOptions",
    "ModelOutput",
    "ModelOutputStatus",
    "Request",
    "RequestAugmented",
    "RequestStatus",
    "Breach",
    "ObjectiveCategory",
    "QuickStaffing",
    "Schedule",
    "SolveDetailsStatus",
    "ScheduleSolveStatus",
    "ScheduleStatus",
    "SolveDetails",
    "Variable",
    "WorkTimeTable",
    "WorkTimeTableData",
    "LinkShift",
    "Shift",
    "ShiftLeaveType",
    "ShiftRestType",
    "ShiftType",
    "Staffing",
    "HeaderUnitOptions",
    "StatsOptions",
    "StatsTimeFrameOptions",
    "StatsUnitOptions",
    "Stats",
    "StatsHeader",
    "StatsValue",
    "TaskServices",
    "Specialty",
    "Team",
    "Language",
    "PasswordData",
    "User",
    "UserAuth",
    "UserDashboard",
    "Worker",
    "WorkerDates",
]
