[pytest]
env =
    # Environment
    ENVIRONMENT=development
    # API:
    API_DOMAIN=0.0.0.0
    API_URL=http://0.0.0.0:4000
    API_PORT=4000
    ORIGINS=http://0.0.0.0:3000
    #CLIENT
    CLIENT_URL=http://0.0.0.0:3000
    #Database:
    DB_URI=mock_db_uri
    # Supertokens config
    ST_CONNECTION_URI=mock_st_uri
    ST_API_KEY=mock_st_api_key
    ST_DASHBOARD_ADMINS=mock_st_dashboard_admins
    ST_COOKIE_DOMAIN=0.0.0.0
    # Permit.io config
    PDP_URL=http://localhost:7766
    PDP_API_KEY=mock_pdp_api_key
    # Uvicorn config
    UVICORN_RELOAD=False
    # Redis config
    REDIS_URL=redis://localhost:6379/0
    RESULT_BACKEND=redis://localhost:6379/0
    # in seconds
    TASK_EXIPRATION=150
