[pytest]
env =
    # Environment
    ENVIRONMENT=development
    # API:
    API_DOMAIN=0.0.0.0
    API_URL=http://0.0.0.0:4000
    API_PORT=4000
    ORIGINS=["http://0.0.0.0:3000"]
    BACKEND_API_KEY_SSM_PARAMETER_NAME=/nsp_pro/dev/backend_api_key
    #CLIENT
    CLIENT_URL=http://0.0.0.0:3000
    #Database:
    DB_URI=mock_db_uri
    # Permit.io config
    PDP_URL=http://localhost:7766
    PDP_API_KEY=mock_pdp_api_key
    # Uvicorn config
    UVICORN_RELOAD=False
    # Redis config
    REDIS_URL=redis://localhost:6379/0
    RESULT_BACKEND=redis://localhost:6379/0
    # in seconds
    TASK_EXIPRATION=150
    # AWS SQS Queues
    SQS_SOLVE_QUEUE_URL=http://sqs.eu-west-3.localhost.localstack.cloud:4566/000000000000/nsp-pro-dev-solve-queue
    SQS_EMAIL_QUEUE_URL=http://sqs.eu-west-3.localhost.localstack.cloud:4566/000000000000/nsp-pro-dev-email-queue