# Justfile for backend solve_service

update-shared:
    echo "Reinstall shared package..."
    uv sync --reinstall-package shared

format:
    echo "Formatting solve_service..."
    uv run ruff format .
    uv run ruff check --fix .

lint:
    echo "Running linter for solve_service..."
    uv run ruff check .

typecheck:
    echo "Running type checker for solve_service..."
    uv run python -m mypy .

test:
    echo "Running tests for solve_service..."
    uv run pytest

all:
    just update-shared
    just format
    just lint
    just typecheck
    just test
    just security

all-no-test:
    just update-shared
    just format
    just lint
    just typecheck

security:
    just audit-deps
    just bandit
    just semgrep

audit-deps:
    echo "Running pip-audit for solve_service..."
    uv run pip-audit

bandit:
    echo "Running bandit for solve_service..."
    uv run bandit -r src/ -ll

semgrep:
    echo "Running semgrep for solve_service..."
    uv run semgrep --config=auto --error src/

dev:
    echo "Starting solve_service (SQS consumer)..."
    uv run python -m src.main --env-file .env.development.tests
