import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SuperTokensProvider } from "../components/supertokensProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SuperTokensProvider>
        <AppRouterCacheProvider>
          <body className={inter.className}>{children}</body>
        </AppRouterCacheProvider>
      </SuperTokensProvider>
    </html>
  );
}
