import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
// Components
import { SuperTokensProvider } from "../components/supertokensProvider";
import { TeamStoreProvider } from "../providers/team-store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SuperTokensProvider>
        <AppRouterCacheProvider>
          <TeamStoreProvider>
            <body className={inter.className}>{children}</body>
          </TeamStoreProvider>
        </AppRouterCacheProvider>
      </SuperTokensProvider>
    </html>
  );
}
