name: Backend - Check
defaults:
  run:
    shell: bash
    working-directory: ./backend

on:
  push:
    branches: '**'
    # branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
    
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', '3.11']
        poetry-version: [1.5.1]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load cached Poetry installation 
      # from https://github.com/marketplace/actions/install-poetry-action#caching-the-poetry-installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-${{ matrix.poetry-version }}-0  # increment to reset cache

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Check coding styles with flake8
      run: poetry run flake8 src

    - name: Check coding styles with black
      run: poetry run black --check src
  
    - name: Check with pylint
      run: poetry run pylint src
  
    - name: Check types with
      run: poetry run mypy src
  