name: Backend - Check
defaults:
  run:
    shell: bash
    working-directory: ./backend

on:
  push:
    branches: '**'
    # branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
    
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        poetry-version: [1.8.2]


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load cached Poetry installation 
      # from https://github.com/marketplace/actions/install-poetry-action#caching-the-poetry-installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-${{ matrix.poetry-version }}-0  # increment to reset cache

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ matrix.poetry-version }}

    - name: Load cached Poetry dependencies
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          backend/api_gateway/.venv
          backend/processing_engine/.venv
          backend/storage_service/.venv
          backend/shared/.venv
        key: poetry-dependencies-${{ matrix.python-version }}-${{ matrix.poetry-version }}-0

    - name: Install dependencies for shared
      run: poetry install
      working-directory: ./backend/shared

    - name: Build shared package
      run: poetry build
      working-directory: ./backend/shared

    - name: Install dependencies for api_gateway
      run: poetry install
      working-directory: ./backend/api_gateway

    - name: Install dependencies for data_fetcher
      run: poetry install
      working-directory: ./backend/data_fetcher
  
    - name: Install dependencies for processing_engine
      run: poetry install
      working-directory: ./backend/processing_engine
  
    - name: Install dependencies for storage_service
      run: poetry install
      working-directory: ./backend/storage_service
  
    - name: Run checks
      run: make check
      working-directory: ./backend
  